import { Terraria, Modules } from './../../../../TL/ModImports.js';
import { ModItem } from './../../../../TL/ModItem.js';
import { ModProjectile } from './../../../../TL/ModProjectile.js';
const { Vector2 }=Modules;const NewProjectile=Terraria.Projectile['int NewProjectile(IEntitySource spawnSource, Vector2 position, Vector2 velocity, int Type, int Damage, float KnockBack, int Owner, float ai0, float ai1, float ai2, NewProjectileModifier modifer)'];function N(v,f=0){const n=Number(v);return Number.isFinite(n)?n:f;}function norm(v){const x=N(v&&v.X),y=N(v&&v.Y),d=Math.sqrt(x*x+y*y);return d>.001?Vector2.new(x/d,y/d):Vector2.new(1,0);}function src(p,i){try{return p['IEntitySource GetProjectileSource_Item(Item item)'](i);}catch(_){return null;}}
export class NightsRay extends ModItem{
 constructor(){super();this.Texture='Items/Weapons/Magic/NightsRay';this.ResearchUnlockCount=1;}
 SetStaticDefaults(){try{Terraria.Item.staff[this.Type]=true;}catch(_){} }
 SetDefaults(){const i=this.Item;i.width=58;i.height=54;i.damage=20;i.magic=true;i.mana=15;i.useAnimation=20;i.useTime=20;i.useStyle=Terraria.ID.ItemUseStyleID.Shoot;i.noMelee=true;i.knockBack=3.25;i.value=Terraria.Item.buyPrice(0,4,0,0);i.rare=Terraria.ID.ItemRarityID.LightRed;i.UseSound=Terraria.ID.SoundID.Item72;i.autoReuse=true;i.shoot=ModProjectile.getTypeByName('NightsRayBeam');i.shootSpeed=6;this.MenuCategories.push('magic');}
 Shoot(item,player,position,velocity,type,damage,kb){const t=Number(ModProjectile.getTypeByName('NightsRayBeam')||0);if(!(t>0))return false;const v=Vector2.Multiply(norm(velocity),24);NewProjectile(src(player,item),position,v,t,Math.max(1,Math.floor(N(damage)>0?N(damage):N(item.damage,20))),N(kb,3.25),Terraria.PlayerIndex(player),0,0,0,null);return false;}
 AddRecipes(){const gel=ModItem.getTypeByName('PurifiedGel');if(!(gel>0))return;this.CreateRecipe().AddIngredient(Terraria.ID.ItemID.Vilethorn,1).AddIngredient(Terraria.ID.ItemID.MagicMissile,1).AddIngredient(Terraria.ID.ItemID.WandofFrosting,1).AddIngredient(Terraria.ID.ItemID.AmberStaff,1).AddIngredient(gel,10).AddTile(Terraria.ID.TileID.DemonAltar).Register();this.CreateRecipe().AddIngredient(Terraria.ID.ItemID.CrimsonRod,1).AddIngredient(Terraria.ID.ItemID.MagicMissile,1).AddIngredient(Terraria.ID.ItemID.WandofFrosting,1).AddIngredient(Terraria.ID.ItemID.AmberStaff,1).AddIngredient(gel,10).AddTile(Terraria.ID.TileID.DemonAltar).Register();}
}