import { Terraria, Modules } from './../../../TL/ModImports.js';
import { ModProjectile } from './../../../TL/ModProjectile.js';
import { PlayItemSound } from '../../../Common/Snippets/LegacySoundCompat.js';
const { Vector2,Color }=Modules;
const NewProjectile=Terraria.Projectile['int NewProjectile(IEntitySource spawnSource, Vector2 position, Vector2 velocity, int Type, int Damage, float KnockBack, int Owner, float ai0, float ai1, float ai2, NewProjectileModifier modifer)'];
const NewDust=Terraria.Dust['int NewDust(Vector2 Position, int Width, int Height, int Type, float SpeedX, float SpeedY, int Alpha, Color newColor, float Scale)'];
const Active=new Map(), AimSignal=new Map(), State=new Map();
function N(v,f=0){const n=Number(v);return Number.isFinite(n)?n:f;}function K(p){return Math.floor(N(p.whoAmI,-1));}function P(o){try{return Terraria.Main.player[o];}catch(_){return null;}}function Norm(v,fx=1,fy=0){const x=N(v&&v.X),y=N(v&&v.Y),d=Math.sqrt(x*x+y*y);return d>.001?Vector2.new(x/d,y/d):Vector2.new(fx,fy);}function Live(slot,type){try{const p=Terraria.Main.projectile[slot];return !!(p&&p.active&&N(p.type)===N(type));}catch(_){return false;}}
function PickAmmo(player,id){try{const a=Array.from(player.inventory||[]);for(let i=54;i<58&&i<a.length;i++)if(a[i]&&N(a[i].ammo)===N(id)&&N(a[i].stack)>0)return a[i];for(let i=0;i<54&&i<a.length;i++)if(a[i]&&N(a[i].ammo)===N(id)&&N(a[i].stack)>0)return a[i];}catch(_){}return null;}function Consume(a){if(!a||a.consumable!==true||Math.random()<.33)return;try{a.stack=N(a.stack)-1;if(N(a.stack)<=0)a.TurnToAir(true);}catch(_){}}
function Source(p,pl){try{return p.GetProjectileSource_FromThis();}catch(_){}try{return pl.GetProjectileSource_Item(pl.HeldItem);}catch(_){return null;}}
export function RegisterFirestormAim(owner,v){AimSignal.set(Number(owner),Norm(v));}
export function FirestormHoldoutActive(owner){const e=Active.get(Number(owner));if(!e)return false;if(Live(e.slot,e.type))return true;Active.delete(Number(owner));return false;}
export class FirestormCannonHoldout extends ModProjectile{
 constructor(){super();this.Texture='Items/Weapons/Ranged/FirestormCannon';}
 SetDefaults(){const p=this.Projectile;p.width=56;p.height=28;p.friendly=false;p.ranged=true;p.penetrate=-1;p.tileCollide=false;p.ignoreWater=true;p.timeLeft=2;p.aiStyle=-1;}
 CanDamage(){return false;}
 OnSpawn(p){Active.set(Number(p.owner),{slot:K(p),type:N(p.type)});State.set(K(p),{age:0,heat:0,cool:0,warn:false});}
 AI(p){const pl=P(p.owner),s=State.get(K(p))||{age:0,heat:0,cool:0,warn:false};State.set(K(p),s);if(!pl||pl.active===false||pl.dead===true){p.Kill();return;}let aim=AimSignal.get(Number(p.owner));try{if(Number(p.owner)===Number(Terraria.Main.myPlayer)){const m=Terraria.Main.MouseWorld,c=pl.MountedCenter,dx=N(m.X)-N(c.X),dy=N(m.Y)-N(c.Y),d=Math.sqrt(dx*dx+dy*dy);if(d>8)aim=Vector2.new(dx/d,dy/d);}}catch(_){}aim=Norm(aim||p.velocity,N(Terraria.PlayerDirection(pl),1),0);AimSignal.set(Number(p.owner),aim);const dir=N(aim.X)<0?-1:1;Terraria.SetPlayerDirection(pl,dir);p.direction=dir;p.spriteDirection=dir;p.rotation=Math.atan2(N(aim.Y),N(aim.X))+(dir<0?Math.PI:0);p.Center=Vector2.Add(pl.MountedCenter,Vector2.Multiply(aim,12));p.timeLeft=2;pl.heldProj=p.whoAmI;pl.itemTime=2;pl.itemAnimation=2;pl.itemRotation=Math.atan2(N(aim.Y)*dir,N(aim.X)*dir);
 const using=pl.channel===true||pl.controlUseItem===true,ammo=PickAmmo(pl,Terraria.ID.AmmoID.Flare);if(!using||!ammo){p.Kill();return;}s.age++;if(s.age<30)return;s.heat++;if(s.heat>=480){try{pl.AddBuff(Terraria.ID.BuffID.OnFire,180,false);}catch(_){}for(let i=0;i<6;i++)try{NewDust(p.position,p.width,p.height,6,-N(aim.X)*(2+Math.random()*3),-N(aim.Y)*(2+Math.random()*3),0,Color.White,1.2);}catch(_){}p.Kill();return;}if(s.cool>0){s.cool--;return;}const lerp=Math.min(1,Math.max(0,(s.age-30)/90)),rate=Math.max(5,Math.floor(11-(11-5)*lerp));s.cool=rate-1;try{PlayItemSound(11,p.Center,0,.55);}catch(_){}const side=Vector2.new(-N(aim.Y),N(aim.X)),spread=(Math.random()-.5)*(.16+.08*lerp),v=Norm(Vector2.Add(aim,Vector2.Multiply(side,spread))),speed=Math.max(5.5,N(pl.HeldItem&&pl.HeldItem.shootSpeed,5.5)),vel=Vector2.Multiply(v,speed),spawn=Vector2.Add(p.Center,Vector2.Multiply(aim,10)),pt=N(ammo.shoot)>0?N(ammo.shoot):N(Terraria.ID.ProjectileID.Flare,163),dmg=Math.max(1,Math.floor(N(p.damage)+N(ammo.damage))),kb=N(p.knockBack)+N(ammo.knockBack),id=NewProjectile(Source(p,pl),spawn,vel,pt,dmg,kb,p.owner,0,0,1,null);try{const q=Terraria.Main.projectile[id];if(q){q.penetrate=3;q.extraUpdates=1;q.timeLeft=Math.min(N(q.timeLeft,600),600);q.ranged=true;q.netUpdate=true;}}catch(_){}Consume(ammo);}
 OnKill(p){State.delete(K(p));const e=Active.get(Number(p.owner));if(e&&e.slot===K(p))Active.delete(Number(p.owner));}
}
