import { Terraria, Modules } from './../../../TL/ModImports.js';
import { ModProjectile } from './../../../TL/ModProjectile.js';
import { FusionEntityData } from './../../../Core/FusionEntityData.js';
import { PlayItemSound } from './../../../Common/Snippets/LegacySoundCompat.js';
const { Vector2, Color, Rectangle }=Modules;
const SpriteEffects=new NativeClass('Microsoft.Xna.Framework.Graphics','SpriteEffects');
const NewProjectile=Terraria.Projectile['int NewProjectile(IEntitySource spawnSource, Vector2 position, Vector2 velocity, int Type, int Damage, float KnockBack, int Owner, float ai0, float ai1, float ai2, NewProjectileModifier modifer)'];
const NewDust=Terraria.Dust['int NewDust(Vector2 Position, int Width, int Height, int Type, float SpeedX, float SpeedY, int Alpha, Color newColor, float Scale)'];
function N(v,f=0){const n=Number(v);return Number.isFinite(n)?n:f;}function I(v,f=-1){const n=Math.floor(Number(v));return Number.isFinite(n)?n:f;}function owner(p){const i=I(p.owner);try{return i===I(Terraria.Main.myPlayer,-2)?Terraria.Main.LocalPlayer:Terraria.Main.player.get_Item(i);}catch(_){return null;}}function npcAt(i){try{return Terraria.Main.npc.get_Item(I(i));}catch(_){return null;}}function valid(n){try{return !!n&&n.active!==false&&n.friendly!==true&&n.townNPC!==true&&n.dontTakeDamage!==true&&N(n.life)>0;}catch(_){return false;}}function center(e){try{return e.Center;}catch(_){return Vector2.Zero;}}function norm(v,s=1){const x=N(v?.X),y=N(v?.Y),l=Math.sqrt(x*x+y*y)||1;return Vector2.new(x/l*s,y/l*s);}function source(p){try{return p.GetProjectileSource_FromThis();}catch(_){return null;}}function dust(p,id,count=1,scale=1){for(let i=0;i<count;i++)try{NewDust(p.position,p.width,p.height,id,(Math.random()-.5)*3,(Math.random()-.5)*3,100,Color.White,scale);}catch(_){} }
function nearestNPC(c,range){let best=null,d2=range*range;for(let i=0;i<200;i++){const n=npcAt(i);if(!valid(n))continue;const q=center(n),dx=N(q.X)-N(c.X),dy=N(q.Y)-N(c.Y),v=dx*dx+dy*dy;if(v<d2){d2=v;best=n;}}return best;}function ricochetNPC(c,range){let boss=null,bd=range*range,other=null,od=range*range;for(let i=0;i<200;i++){const n=npcAt(i);if(!valid(n))continue;const q=center(n),dx=N(q.X)-N(c.X),dy=N(q.Y)-N(c.Y),d=dx*dx+dy*dy;if(n.boss===true){if(d<bd){bd=d;boss=n;}}else if(d<od){od=d;other=n;}}return boss||other;}
function setArray(holder,name,index,value){try{let a=holder[name],need=I(index,0)+1,len=N(a?.Length,N(a?.length));if(len<need){a=a.cloneResized(need);holder[name]=a;}try{a.set_Item(I(index,0),value);}catch(_){a['void SetValue(Object value, int index)'](value,I(index,0));}return true;}catch(_){return false;}}
const CoinRegistry=new Map();
let CachedRicoshotCoinType=0;
function ricoshotCoinType(){if(!(CachedRicoshotCoinType>0))CachedRicoshotCoinType=Number(ModProjectile.getTypeByName('RicoshotCoin')||0);return CachedRicoshotCoinType;}
function coinSet(ownerId){const key=I(ownerId,-1);let set=CoinRegistry.get(key);if(!set){set=new Set();CoinRegistry.set(key,set);}return set;}
function projectileAt(id){const i=I(id,-1);if(i<0||i>=1000)return null;try{return Terraria.Main.projectile.get_Item(i);}catch(_){try{return Terraria.Main.projectile[i];}catch(__){return null;}}}
export function RegisterRicoshotCoin(p){if(!p)return false;const id=I(p.whoAmI,-1),o=I(p.owner,-1);if(id<0||o<0)return false;coinSet(o).add(id);return true;}
export function GetRicoshotCoinById(ownerId,id){const key=I(ownerId,-1),i=I(id,-1),p=projectileAt(i),t=ricoshotCoinType();if(!p||p.active===false||I(p.owner,-2)!==key||(t>0&&I(p.type,-3)!==t))return null;const s=FusionEntityData.GetProjectileBag(p,'ricoshotCoin',()=>({struck:false,freeze:0}));if(s.struck||N(s.freeze)>0)return null;return p;}
function activeCoinList(ownerId,skip){const key=I(ownerId,-1),set=CoinRegistry.get(key),a=[];if(set){for(const id of Array.from(set)){const p=GetRicoshotCoinById(key,id);if(!p||p===skip){if(!p)set.delete(id);continue;}a.push(p);}if(set.size===0)CoinRegistry.delete(key);}return a;}
// Only used on weapon presses or after a successful ricochet, never every AI update.
// If the registry missed an OnSpawn edge case, perform one native-array recovery scan.
function recoverCoins(ownerId){const key=I(ownerId,-1),t=ricoshotCoinType();if(!(t>0))return [];const a=[];for(let i=0;i<1000;i++){const p=projectileAt(i);if(!p||p.active===false||I(p.owner,-2)!==key||I(p.type,-3)!==t)continue;const s=FusionEntityData.GetProjectileBag(p,'ricoshotCoin',()=>({struck:false,freeze:0}));if(s.struck||N(s.freeze)>0)continue;coinSet(key).add(i);a.push(p);}return a;}
function availableCoins(ownerId,skip){let a=activeCoinList(ownerId,skip);if(a.length===0)a=recoverCoins(ownerId).filter(p=>p!==skip);return a;}
export function ActiveRicoshotCoinCount(ownerId){return availableCoins(ownerId,null).length;}
export function FindNearestRicoshotCoinId(ownerId,from){try{const c=nearestCoin(from||Vector2.Zero,ownerId,null,1200);return c?I(c.whoAmI,-1):-1;}catch(_){return -1;}}
export function NearestRicoshotCoin(ownerId,from){try{return nearestCoin(from,ownerId,null,1200);}catch(_){return null;}}
function segmentDistanceSq(px,py,ax,ay,bx,by){const abx=bx-ax,aby=by-ay,apx=px-ax,apy=py-ay,d=abx*abx+aby*aby;if(d<=.0001){const dx=px-ax,dy=py-ay;return dx*dx+dy*dy;}let t=(apx*abx+apy*aby)/d;t=Math.max(0,Math.min(1,t));const x=ax+abx*t,y=ay+aby*t,dx=px-x,dy=py-y;return dx*dx+dy*dy;}
function predictiveTargetPosition(start,n,speed){const c=center(n),v=n?.velocity||Vector2.Zero,dx=N(c.X)-N(start.X),dy=N(c.Y)-N(start.Y),dist=Math.sqrt(dx*dx+dy*dy),travel=dist/Math.max(1,speed),lead=.1*travel;return Vector2.new(N(c.X)+N(v.X)*lead,N(c.Y)+N(v.Y)*lead);}
function nearestCoin(start,ownerId,skip,range=1000){let best=null,d2=range*range;for(const c of availableCoins(ownerId,skip)){const q=center(c),dx=N(q.X)-N(start.X),dy=N(q.Y)-N(start.Y),v=dx*dx+dy*dy;if(v<d2){d2=v;best=c;}}return best;}

let RicoshotTexture=null;function ricoshotTexture(){if(RicoshotTexture)return RicoshotTexture;try{RicoshotTexture=tl.texture.load('Textures/Projectiles/Ranged/RicoshotCoin.png');}catch(_){}return RicoshotTexture;}let MarksmanTexture=null;function marksmanTexture(){if(MarksmanTexture)return MarksmanTexture;try{MarksmanTexture=tl.texture.load('Textures/ExtraTextures/TinyGreyscaleCircle.png');}catch(_){}return MarksmanTexture;}
export class MarksmanShot extends ModProjectile{
 constructor(){super();this.Texture='ExtraTextures/TinyGreyscaleCircle';}
 SetDefaults(){const p=this.Projectile;p.width=p.height=12;p.ranged=true;p.friendly=true;p.hostile=false;p.penetrate=-1;p.usesLocalNPCImmunity=true;p.localNPCHitCooldown=-1;p.timeLeft=240;p.extraUpdates=1;p.alpha=0;p.scale=.55;p.tileCollide=true;p.aiStyle=-1;p.light=.25;}
 OnSpawn(p){const raw=I(p.ai?.val0,0),targetCoinId=raw>0?raw-1:-1;FusionEntityData.GetProjectileBag(p,'marksman',()=>({hit:false,freeze:0,ricochets:0,baseDamage:Math.max(1,I(p.damage,18)),bonus:0,resumeX:N(p.velocity.X),resumeY:N(p.velocity.Y),age:0,targetCoinId,targetNpcId:-1,homeTicks:0}));}
 RicochetCoin(p,s,struck){
  if(!struck||struck.active===false)return false;const cs=FusionEntityData.GetProjectileBag(struck,'ricoshotCoin',()=>({struck:false,freeze:0}));if(cs.struck)return false;cs.struck=true;
  const impact=center(struck);p.Center=impact;try{struck.Kill();}catch(_){struck.active=false;}s.ricochets++;s.bonus+=s.ricochets===1?1.25:.25;p.damage=Math.max(1,Math.floor(N(s.baseDamage,18)*(1+N(s.bonus))));
  const speed=Math.max(28,Math.hypot(N(p.velocity.X),N(p.velocity.Y))),coin=nearestCoin(impact,p.owner,struck,1000);let targetPos=null,targetNpc=null;
  if(coin)targetPos=center(coin);else{targetNpc=ricochetNPC(impact,2000);if(targetNpc)targetPos=predictiveTargetPosition(impact,targetNpc,speed);}
  if(targetPos){const v=norm(Vector2.new(N(targetPos.X)-N(impact.X),N(targetPos.Y)-N(impact.Y)),speed);s.resumeX=N(v.X);s.resumeY=N(v.Y);}else{s.resumeX=N(p.velocity.X);s.resumeY=N(p.velocity.Y);}
  s.targetCoinId=coin?I(coin.whoAmI,-1):-1;s.targetNpcId=targetNpc?I(targetNpc.whoAmI,-1):-1;s.homeTicks=targetNpc?28:0;s.freeze=6;p.velocity=Vector2.Zero;p.tileCollide=false;try{PlayItemSound(35,impact,.25,.55);}catch(_){}dust(p,Terraria.ID.DustID.GoldCoin,1,.65);p.netUpdate=true;return true;
 }
 AI(p){const s=FusionEntityData.GetProjectileBag(p,'marksman',()=>({hit:false,freeze:0,ricochets:0,baseDamage:Math.max(1,I(p.damage,18)),bonus:0,resumeX:N(p.velocity.X),resumeY:N(p.velocity.Y),age:0,targetCoinId:-1,targetNpcId:-1,homeTicks:0}));s.age++;
  if(s.freeze>0){s.freeze--;p.velocity=Vector2.Zero;if(s.freeze<=0)p.velocity=Vector2.new(N(s.resumeX),N(s.resumeY));return;}
  if(I(s.targetCoinId,-1)>=0){p.tileCollide=false;const coin=GetRicoshotCoinById(p.owner,s.targetCoinId);if(coin){const a=center(p),b=center(coin),dx=N(b.X)-N(a.X),dy=N(b.Y)-N(a.Y),dist=Math.sqrt(dx*dx+dy*dy),speed=Math.max(28,Math.hypot(N(p.velocity.X),N(p.velocity.Y)));if(dist>0)p.velocity=Vector2.new(dx/dist*speed,dy/dist*speed);if(dist<=Math.max(24,speed*.9)){this.RicochetCoin(p,s,coin);return;}}else s.targetCoinId=-1;}
  if(I(s.targetCoinId,-1)<0&&I(s.targetNpcId,-1)>=0&&I(s.homeTicks,0)>0){const n=npcAt(s.targetNpcId);if(valid(n)){const a=center(p),speed=Math.max(28,Math.hypot(N(p.velocity.X),N(p.velocity.Y))),q=predictiveTargetPosition(a,n,speed),v=norm(Vector2.new(N(q.X)-N(a.X),N(q.Y)-N(a.Y)),speed);p.velocity=v;p.tileCollide=false;s.homeTicks--;if(s.homeTicks<=0)p.tileCollide=true;}else{s.targetNpcId=-1;s.homeTicks=0;p.tileCollide=true;}}
  else if(I(s.targetCoinId,-1)<0&&I(s.targetNpcId,-1)<0)p.tileCollide=true;
  if(s.targetCoinId<0&&s.ricochets<4){const a=center(p),next=Vector2.new(N(a.X)+N(p.velocity.X),N(a.Y)+N(p.velocity.Y));let struck=null,bestT=2;for(const coin of activeCoinList(p.owner,null)){const b=center(coin),r=Math.max(16,N(coin.width,22)*.65),d2=segmentDistanceSq(N(b.X),N(b.Y),N(a.X),N(a.Y),N(next.X),N(next.Y));if(d2<=r*r){const total=(N(next.X)-N(a.X))**2+(N(next.Y)-N(a.Y))**2||1,t=((N(b.X)-N(a.X))*(N(next.X)-N(a.X))+(N(b.Y)-N(a.Y))*(N(next.Y)-N(a.Y)))/total;if(t<bestT){bestT=t;struck=coin;}}}if(struck)this.RicochetCoin(p,s,struck);}
 }
 CanDamage(p){return FusionEntityData.GetProjectileBag(p,'marksman',()=>({hit:false})).hit?false:null;}
 OnHitNPC(p,n){const s=FusionEntityData.GetProjectileBag(p,'marksman',()=>({hit:false}));s.hit=true;s.targetNpcId=-1;s.homeTicks=0;p.velocity=Vector2.Zero;p.tileCollide=false;try{n.AddBuff(Terraria.ID.BuffID.Midas,60,false);}catch(_){}try{PlayItemSound(35,p.Center,.1,.4);}catch(_){}dust(p,Terraria.ID.DustID.GoldCoin,1,.65);p.timeLeft=Math.min(I(p.timeLeft,12),12);}
 OnTileCollide(p){p.velocity=Vector2.Zero;p.tileCollide=false;p.timeLeft=Math.min(I(p.timeLeft,12),12);return false;}
 PreDraw(p,lightColor){const tex=marksmanTexture();if(!tex)return true;try{const draw=Terraria.Main.spriteBatch['void Draw(Texture2D texture, Vector2 position, Nullable`1 sourceRectangle, Color color, float rotation, Vector2 origin, float scale, SpriteEffects effects, float layerDepth)'];if(!draw)return true;const v=norm(p.velocity,1),base=Vector2.new(N(p.Center.X)-N(Terraria.Main.screenPosition.X),N(p.Center.Y)-N(Terraria.Main.screenPosition.Y)+N(p.gfxOffY)),origin=Vector2.new(N(tex.Width)/2,N(tex.Height)/2),cols=[Color.new(255,238,150,255),Color.new(255,220,95,190),Color.new(255,200,70,120),Color.new(255,180,50,60)],sc=[.38,.30,.22,.14];for(let i=3;i>=0;i--){const pos=Vector2.new(N(base.X)-N(v.X)*i*6,N(base.Y)-N(v.Y)*i*6);draw(tex,pos,null,cols[i],0,origin,sc[i],SpriteEffects.None,0);}return false;}catch(_){return true;}}
}

export class RicoshotCoin extends ModProjectile{
 constructor(){super();this.Texture='Projectiles/Ranged/RicoshotCoin';}
 SetStaticDefaults(){setArray(Terraria.Main,'projFrames',this.Type,8);}
 SetDefaults(){const p=this.Projectile;p.width=p.height=22;p.scale=1.1;p.friendly=true;p.hostile=false;p.penetrate=-1;p.timeLeft=420;p.tileCollide=true;p.ignoreWater=false;p.aiStyle=-1;p.extraUpdates=0;}
 OnSpawn(p){FusionEntityData.GetProjectileBag(p,'ricoshotCoin',()=>({age:0,struck:false,freeze:0}));RegisterRicoshotCoin(p);}
 AI(p){const s=FusionEntityData.GetProjectileBag(p,'ricoshotCoin',()=>({age:0,struck:false,freeze:0}));s.age++;if(s.freeze>0){s.freeze--;p.velocity=Vector2.Zero;if(s.freeze<=0)p.Kill();return;}p.frameCounter=N(p.frameCounter)+1;if(N(p.frameCounter)>8){p.frameCounter=0;p.frame=(I(p.frame,0)+1)%8;}p.rotation=N(p.velocity.X)*.5;p.velocity=Vector2.new(N(p.velocity.X),N(p.velocity.Y)+.4);if((s.age%30)===0)dust(p,Terraria.ID.DustID.CopperCoin||11,1,.65);}
 CanDamage(){return false;}
 OnTileCollide(){return true;}
 PreDraw(p,lightColor){const tex=ricoshotTexture();if(!tex)return true;try{const draw=Terraria.Main.spriteBatch['void Draw(Texture2D texture, Vector2 position, Nullable`1 sourceRectangle, Color color, float rotation, Vector2 origin, float scale, SpriteEffects effects, float layerDepth)'];if(!draw)return true;const frame=Math.max(0,Math.min(7,I(p.frame,0))),coin=Math.max(0,Math.min(2,I(p.ai?.val0,0))),rect=Rectangle.new(coin*14,frame*16,12,14),pos=Vector2.new(N(p.Center.X)-N(Terraria.Main.screenPosition.X),N(p.Center.Y)-N(Terraria.Main.screenPosition.Y)+N(p.gfxOffY));draw(tex,pos,rect,lightColor,N(p.rotation),Vector2.new(6,7),N(p.scale,1.1),SpriteEffects.None,0);return false;}catch(_){return true;}}
 OnKill(p){const key=I(p.owner,-1),set=CoinRegistry.get(key);if(set){set.delete(I(p.whoAmI,-1));if(set.size===0)CoinRegistry.delete(key);}}
}
let SlagHoldTexture=null;function slagHoldTex(){if(SlagHoldTexture)return SlagHoldTexture;try{SlagHoldTexture=tl.texture.load('Textures/Projectiles/Ranged/SlagfireDouserHoldout.png');}catch(_){}return SlagHoldTexture;}
const SlagHB=new Map();
export function SlagfireDouserHoldoutActive(o){const now=I(Terraria.Main.GameUpdateCount,0),t=I(SlagHB.get(Number(o)),-9999);if(now-t<=3)return true;SlagHB.delete(Number(o));return false;}
export class SlagfireDouserHoldout extends ModProjectile{
 constructor(){super();this.Texture='Projectiles/Ranged/SlagfireDouserHoldout';this.ShotType=0;}
 PostSetupContent(){this.ShotType=Number(ModProjectile.getTypeByName('Slagfire')||0);}
 SetDefaults(){const p=this.Projectile;p.width=104;p.height=34;p.friendly=false;p.hostile=false;p.penetrate=-1;p.timeLeft=2;p.tileCollide=false;p.ignoreWater=true;p.aiStyle=-1;}
 OnSpawn(p){SlagHB.set(Number(p.owner),I(Terraria.Main.GameUpdateCount,0));FusionEntityData.GetProjectileBag(p,'slagHold',()=>({age:0}));}
 AI(p){const pl=owner(p),s=FusionEntityData.GetProjectileBag(p,'slagHold',()=>({age:0}));if(!pl||pl.active===false||pl.dead===true||(!pl.channel&&!pl.controlUseItem)){p.Kill();return;}s.age++;SlagHB.set(Number(p.owner),I(Terraria.Main.GameUpdateCount,0));p.timeLeft=2;let a=norm(p.velocity);try{const c=pl.MountedCenter,m=Terraria.Main.MouseWorld;a=norm(Vector2.new(N(m.X)-N(c.X),N(m.Y)-N(c.Y)));}catch(_){}const dir=N(a.X)>=0?1:-1,grav=N(pl.gravDir,1)<0?-1:1,rot=Math.atan2(N(a.Y),N(a.X)),lookUp=Math.max(-1,Math.min(1,N(a.Y)*-grav)),absUp=Math.abs(lookUp);const armX=(-25*absUp)*dir,armY=(-2+(lookUp>0?-24:24)*absUp)*grav,lenX=Math.cos(rot)*12,lenY=Math.sin(rot)*12;p.velocity=a;p.rotation=rot;p.spriteDirection=dir;p.Center=Vector2.new(N(pl.MountedCenter.X)+lenX+armX,N(pl.MountedCenter.Y)+lenY+armY);try{Terraria.SetPlayerDirection(pl,dir);}catch(_){}try{pl.heldProj=p.whoAmI;pl.itemTime=2;pl.itemAnimation=2;const arm=(rot-Math.PI/2)*grav+(grav<0?Math.PI:0),stretch=Terraria.Player.CompositeArmStretchAmount.Full;pl.SetCompositeArmFront(true,stretch,arm+.14*dir);pl.SetCompositeArmBack(true,stretch,arm);}catch(_){}const cycle=s.age%46;if(cycle>=30&&cycle<46&&(cycle-30)%4===0&&I(p.owner)===I(Terraria.Main.myPlayer)){if(!(this.ShotType>0))this.ShotType=Number(ModProjectile.getTypeByName('Slagfire')||0);if(this.ShotType>0){const ang=(Math.random()-.5)*.19,c=Math.cos(ang),q=Math.sin(ang),v=Vector2.new((N(a.X)*c-N(a.Y)*q)*13,(N(a.X)*q+N(a.Y)*c)*13),tip=Vector2.new(N(p.Center.X)+25*dir+N(a.X)*(35-24*grav),N(p.Center.Y)-5+N(a.Y)*(35-24*grav));NewProjectile(source(p),tip,v,this.ShotType,Math.max(1,I(p.damage,5)),N(p.knockBack,2),p.owner,0,0,0,null);try{PlayItemSound(61,p.Center,.1,.55);}catch(_){} }} }
 CanDamage(){return false;}
 PreDraw(p,lightColor){const tex=slagHoldTex();if(!tex)return true;try{const draw=Terraria.Main.spriteBatch['void Draw(Texture2D texture, Vector2 position, Nullable`1 sourceRectangle, Color color, float rotation, Vector2 origin, float scale, SpriteEffects effects, float layerDepth)'];if(!draw)return true;const pl=owner(p),dir=I(p.spriteDirection,1)<0?-1:1,grav=N(pl?.gravDir,1)<0?-1:1,pos=Vector2.new(N(p.Center.X)-N(Terraria.Main.screenPosition.X)+25*dir,N(p.Center.Y)-N(Terraria.Main.screenPosition.Y)+N(p.gfxOffY)),origin=Vector2.new(N(tex.Width)/2,N(tex.Height)/2),rot=N(p.rotation)+(dir<0?Math.PI:0),fx=dir*grav<0?SpriteEffects.FlipHorizontally:SpriteEffects.None;draw(tex,pos,null,lightColor,rot,origin,N(p.scale,1)*grav,fx,0);return false;}catch(_){return true;}}
 OnKill(p){SlagHB.delete(Number(p.owner));}
}
export class Slagfire extends ModProjectile{
 constructor(){super();this.Texture='ExtraTextures/TinyGreyscaleCircle';}
 SetDefaults(){const p=this.Projectile;p.width=p.height=32;p.friendly=true;p.hostile=false;p.ranged=true;p.ignoreWater=true;p.extraUpdates=1;p.tileCollide=false;p.timeLeft=240;p.aiStyle=-1;p.usesLocalNPCImmunity=true;p.localNPCHitCooldown=10;}
 AI(p){const s=FusionEntityData.GetProjectileBag(p,'slagfire',()=>({age:0}));s.age++;if(s.age>=4)p.tileCollide=true;p.scale=N(p.scale,1)-.001;if(N(p.scale)<=0){p.Kill();return;}if(s.age>=10)p.velocity=Vector2.new(N(p.velocity.X),N(p.velocity.Y)+.2);dust(p,Terraria.ID.DustID.Torch,2,.8);}
 OnHitNPC(p,n){try{n.AddBuff(Terraria.ID.BuffID.OnFire3||Terraria.ID.BuffID.OnFire,600,false);}catch(_){}if(N(n?.type)===N(Terraria.ID.NPCID.Guide)){try{n['double StrikeNPC(int Damage, float knockBack, int hitDirection, bool crit, bool noEffect, bool fromNet, int owner)'](Math.max(1,I(p.damage,5)*24),N(p.knockBack,2),I(p.direction,1),false,false,false,I(p.owner));if(N(n.life)<=0){const pl=owner(p);if(pl)Terraria.NPC.SpawnWOF(pl.Center);}}catch(_){}}dust(p,Terraria.ID.DustID.Torch,6,1.2);}
 OnTileCollide(){return true;}
 OnKill(p){dust(p,Terraria.ID.DustID.Torch,8,1.2);}
}
