import { Terraria, Modules } from './../../../TL/ModImports.js';
import { ModProjectile } from './../../../TL/ModProjectile.js';
import { FusionEntityData } from './../../../Core/FusionEntityData.js';
import { PlayItemSound } from './../../../Common/Snippets/LegacySoundCompat.js';
const { Vector2,Color }=Modules;const NewProjectile=Terraria.Projectile['int NewProjectile(IEntitySource spawnSource, Vector2 position, Vector2 velocity, int Type, int Damage, float KnockBack, int Owner, float ai0, float ai1, float ai2, NewProjectileModifier modifer)'];const NewDust=Terraria.Dust['int NewDust(Vector2 Position, int Width, int Height, int Type, float SpeedX, float SpeedY, int Alpha, Color newColor, float Scale)'];const Active=new Map(),Aim=new Map();function N(v,f=0){const n=Number(v);return Number.isFinite(n)?n:f;}function norm(v,fx=1,fy=0){const x=N(v&&v.X),y=N(v&&v.Y),d=Math.sqrt(x*x+y*y);return d>.001?Vector2.new(x/d,y/d):Vector2.new(fx,fy);}function player(o){try{return Terraria.Main.player[o];}catch(_){return null;}}function live(slot,type){try{const p=Terraria.Main.projectile[slot];return !!(p&&p.active&&N(p.type)===N(type));}catch(_){return false;}}function source(p){try{return p.GetProjectileSource_FromThis();}catch(_){return null;}}function rotate(v,a){const c=Math.cos(a),s=Math.sin(a),x=N(v.X),y=N(v.Y);return Vector2.new(x*c-y*s,x*s+y*c);}export function RegisterPumplerAim(o,v){Aim.set(Number(o),norm(v));}export function PumplerHoldoutActive(o){const e=Active.get(Number(o));if(!e)return false;if(live(e.slot,e.type))return true;Active.delete(Number(o));return false;}
export class PumplerHoldout extends ModProjectile{
 constructor(){super();this.Texture='Items/Weapons/Ranged/Pumpler';}
 SetDefaults(){const p=this.Projectile;p.width=72;p.height=34;p.friendly=false;p.ranged=true;p.penetrate=-1;p.tileCollide=false;p.ignoreWater=true;p.timeLeft=2;p.aiStyle=-1;}
 CanDamage(){return false;}
 OnSpawn(p){Active.set(Number(p.owner),{slot:Math.floor(N(p.whoAmI,-1)),type:N(p.type)});FusionEntityData.GetProjectileBag(p,'pumpler',()=>({loaded:0,loadTimer:30,afterMax:0,firing:false,total:0,index:0,cool:0}));}
 AI(p){const pl=player(p.owner),s=FusionEntityData.GetProjectileBag(p,'pumpler',()=>({loaded:0,loadTimer:30,afterMax:0,firing:false,total:0,index:0,cool:0}));if(!pl||pl.dead){p.Kill();return;}let a=Aim.get(Number(p.owner));try{if(Number(p.owner)===Number(Terraria.Main.myPlayer)){const m=Terraria.Main.MouseWorld,c=pl.MountedCenter,dx=N(m.X)-N(c.X),dy=N(m.Y)-N(c.Y),d=Math.sqrt(dx*dx+dy*dy);if(d>8)a=Vector2.new(dx/d,dy/d);}}catch(_){}a=norm(a||p.velocity,N(Terraria.PlayerDirection(pl),1),0);Aim.set(Number(p.owner),a);const dir=N(a.X)<0?-1:1;Terraria.SetPlayerDirection(pl,dir);p.direction=p.spriteDirection=dir;p.rotation=Math.atan2(N(a.Y),N(a.X))+(dir<0?Math.PI:0);p.Center=Vector2.Add(pl.MountedCenter,Vector2.Multiply(a,30));p.timeLeft=2;pl.heldProj=p.whoAmI;pl.itemTime=2;pl.itemAnimation=2;pl.itemRotation=Math.atan2(N(a.Y)*dir,N(a.X)*dir);
  const using=!!pl.channel||!!pl.controlUseItem;if(!s.firing&&using){s.loadTimer--;if(s.loaded<5&&s.loadTimer<=0){s.loaded++;s.loadTimer=Math.max(11,Math.round(30*Math.pow(.85,s.loaded)));try{PlayItemSound(108,p.Center,0,.3);}catch(_){}for(let i=0;i<2;i++)try{NewDust(p.position,p.width,p.height,6,0,-1,80,Color.White,.7);}catch(_){} }if(s.loaded>=5){s.afterMax++;if(s.afterMax>=160)this.StartFire(s);}return;}
  if(!s.firing){if(s.loaded<=0){p.Kill();return;}this.StartFire(s);}if(s.cool>0){s.cool--;return;}if(s.index>=s.total){p.Kill();return;}const spread=s.total<=1?0:(-Math.PI/12+(Math.PI/6)*(s.index/(s.total-1))),v=Vector2.Multiply(rotate(a,spread),16.5),t=Number(ModProjectile.getTypeByName('PumplerGrenade')||0),spawn=Vector2.Add(p.Center,Vector2.Multiply(a,24));if(t>0)NewProjectile(source(p),spawn,v,t,Math.max(1,N(p.damage,26)),N(p.knockBack,1.25),p.owner,0,0,0,null);try{PlayItemSound(96,p.Center,0,.55);}catch(_){}s.index++;s.cool=3;}
 StartFire(s){s.firing=true;s.total=s.loaded;s.index=0;s.cool=0;}
 OnKill(p){const e=Active.get(Number(p.owner));if(e&&e.slot===Math.floor(N(p.whoAmI,-1)))Active.delete(Number(p.owner));}
}
export class PumplerGrenade extends ModProjectile{
 constructor(){super();this.Texture='Projectiles/Ranged/PumplerGrenade';}
 SetDefaults(){const p=this.Projectile;p.width=26;p.height=26;p.friendly=true;p.ranged=true;p.timeLeft=180;p.penetrate=-1;p.ignoreWater=true;p.usesLocalNPCImmunity=true;p.localNPCHitCooldown=20;p.aiStyle=-1;}
 OnSpawn(p){FusionEntityData.GetProjectileBag(p,'pumplerGrenade',()=>({age:0,exploded:false,bounces:0}));}
 AI(p){const s=FusionEntityData.GetProjectileBag(p,'pumplerGrenade',()=>({age:0,exploded:false,bounces:0}));s.age++;if(s.exploded){p.velocity=Vector2.Zero;p.tileCollide=false;return;}p.rotation=Math.atan2(N(p.velocity.Y),N(p.velocity.X))+Math.PI/2;if(s.age>8)p.velocity=Vector2.new(N(p.velocity.X)*.995,Math.min(16,N(p.velocity.Y)+.4));if(N(p.timeLeft)<=2)this.Explode(p,false);}
 Explode(p,npc){const s=FusionEntityData.GetProjectileBag(p,'pumplerGrenade',()=>({age:0,exploded:false,bounces:0}));if(s.exploded)return;s.exploded=true;const size=npc?128:160,cc=p.Center;p.width=size;p.height=size;p.Center=cc;p.velocity=Vector2.Zero;p.tileCollide=false;p.timeLeft=4;p.penetrate=-1;try{PlayItemSound(14,cc,0,.65);}catch(_){}for(let i=0;i<8;i++){const a=Math.random()*Math.PI*2,sp=2+Math.random()*5;try{NewDust(p.position,p.width,p.height,6,Math.cos(a)*sp,Math.sin(a)*sp,100,Color.White,1);}catch(_){}}}
 OnHitNPC(p){const s=FusionEntityData.GetProjectileBag(p,'pumplerGrenade',()=>({age:0,exploded:false,bounces:0}));if(!s.exploded)this.Explode(p,true);}
 OnTileCollide(p,old){const s=FusionEntityData.GetProjectileBag(p,'pumplerGrenade',()=>({age:0,exploded:false,bounces:0}));if(s.exploded)return false;s.bounces++;if(s.bounces>=2||Math.abs(N(old.Y))<2.5){this.Explode(p,false);return false;}p.velocity=Vector2.new(-N(old.X)*.45,-N(old.Y)*.45);return false;}
}
