import { Terraria, Modules } from './../../../../TL/ModImports.js';
import { ModItem } from './../../../../TL/ModItem.js';
import { ModProjectile } from './../../../../TL/ModProjectile.js';
const { Vector2 }=Modules;
const NewProjectile=Terraria.Projectile['int NewProjectile(IEntitySource spawnSource, Vector2 position, Vector2 velocity, int Type, int Damage, float KnockBack, int Owner, float ai0, float ai1, float ai2, NewProjectileModifier modifer)'];
function N(v,f=0){const n=Number(v);return Number.isFinite(n)?n:f;}function Inv(p){try{return Array.from(p.inventory||[]);}catch(_){return [];}}function Ammo(p,id){const a=Inv(p);for(let i=54;i<58&&i<a.length;i++){if(a[i]&&N(a[i].ammo)===N(id)&&N(a[i].stack)>0)return a[i];}for(let i=0;i<54&&i<a.length;i++){if(a[i]&&N(a[i].ammo)===N(id)&&N(a[i].stack)>0)return a[i];}return null;}function Save(p){try{if(p.ammoBox&&Math.random()<.2)return true;}catch(_){}try{if(p.ammoPotion&&Math.random()<.2)return true;}catch(_){}try{if(p.chloroAmmoCost80&&Math.random()<.2)return true;}catch(_){}try{if(p.ammoCost80&&Math.random()<.2)return true;}catch(_){}try{if(p.ammoCost75&&Math.random()<.25)return true;}catch(_){}return false;}function Consume(p,a){if(!a||a.consumable!==true||Save(p))return;try{a.stack=N(a.stack)-1;if(N(a.stack)<=0)a.TurnToAir(true);}catch(_){}}function Source(p,i){try{return p['IEntitySource GetProjectileSource_Item(Item item)'](i);}catch(_){}try{return null;}catch(_){return null;}}
export class AquashardShotgun extends ModItem{
 constructor(){super();this.Texture='Items/Weapons/Ranged/AquashardShotgun';this.ResearchUnlockCount=1;}
 SetDefaults(){const i=this.Item;i.width=62;i.height=26;i.damage=12;i.ranged=true;i.crit=6;i.useTime=30;i.useAnimation=30;i.useStyle=Terraria.ID.ItemUseStyleID.Shoot;i.noMelee=true;i.knockBack=5.5;i.value=Terraria.Item.buyPrice(0,5,0,0);i.rare=Terraria.ID.ItemRarityID.Orange;i.UseSound=Terraria.ID.SoundID.Item61;i.autoReuse=true;i.shoot=ModProjectile.getTypeByName('Aquashard');i.shootSpeed=30;i.useAmmo=Terraria.ID.AmmoID.Bullet;this.MenuCategories.push('ranged');}
 HoldoutOffset(){return {X:-10,Y:0};}
 CanUseItem(item,player){return Ammo(player,item.useAmmo)!=null;}
 Shoot(item,player,position,velocity,type,damage,knockBack){const a=Ammo(player,item.useAmmo);if(!a)return false;const src=Source(player,item),owner=Terraria.PlayerIndex(player),ranged=Math.max(0,N(player.rangedDamage,1)),dmg=Math.max(1,Math.floor(N(damage)+N(a.damage)*ranged)),kb=N(knockBack)+N(a.knockBack),baseType=N(a.shoot)>0?N(a.shoot):N(type),normalBullet=N(Terraria.ID.ProjectileID.Bullet,14),shotType=baseType===normalBullet?N(ModProjectile.getTypeByName('Aquashard')):baseType;for(let n=0;n<2;n++){NewProjectile(src,position,Vector2.new(N(velocity.X)+(Math.random()*4-2),N(velocity.Y)+(Math.random()*4-2)),shotType,dmg,kb,owner,0,0,0,null);}Consume(player,a);return false;}
 AddRecipes(){this.CreateRecipe().AddIngredient(964,1).AddIngredient(ModItem.getTypeByName('AerialiteBar'),2).AddIngredient(ModItem.getTypeByName('SeaPrism'),10).AddTile(Terraria.ID.TileID.Anvils).Register();}
}
