import { Terraria, Modules } from './../../../../TL/ModImports.js';
import { ModItem } from './../../../../TL/ModItem.js';
import { ModProjectile } from './../../../../TL/ModProjectile.js';
const { Vector2 }=Modules;
const NewProjectile=Terraria.Projectile['int NewProjectile(IEntitySource spawnSource, Vector2 position, Vector2 velocity, int Type, int Damage, float KnockBack, int Owner, float ai0, float ai1, float ai2, NewProjectileModifier modifer)'];
function N(v,f=0){const n=Number(v);return Number.isFinite(n)?n:f;}function Inv(p){try{return Array.from(p.inventory||[]);}catch(_){return [];}}function Ammo5(p,id){const a=Inv(p);for(let i=54;i<58&&i<a.length;i++){if(a[i]&&N(a[i].ammo)===N(id)&&(N(a[i].stack)>=5||a[i].consumable!==true))return a[i];}for(let i=0;i<54&&i<a.length;i++){if(a[i]&&N(a[i].ammo)===N(id)&&(N(a[i].stack)>=5||a[i].consumable!==true))return a[i];}return null;}function Save(p){try{if(p.ammoBox&&Math.random()<.2)return true;}catch(_){}try{if(p.ammoPotion&&Math.random()<.2)return true;}catch(_){}try{if(p.chloroAmmoCost80&&Math.random()<.2)return true;}catch(_){}try{if(p.ammoCost80&&Math.random()<.2)return true;}catch(_){}try{if(p.ammoCost75&&Math.random()<.25)return true;}catch(_){}return false;}function Consume5(p,a){if(!a||a.consumable!==true||Save(p))return;try{a.stack=N(a.stack)-5;if(N(a.stack)<=0)a.TurnToAir(true);}catch(_){}}function Source(p,i){try{return p['IEntitySource GetProjectileSource_Item(Item item)'](i);}catch(_){}try{return null;}catch(_){return null;}}
export class BulletFilledShotgun extends ModItem{
 constructor(){super();this.Texture='Items/Weapons/Ranged/BulletFilledShotgun';this.ResearchUnlockCount=1;}
 SetDefaults(){const i=this.Item;i.width=64;i.height=24;i.damage=1;i.ranged=true;i.useAnimation=75;i.useTime=75;i.knockBack=.25;i.shoot=ModProjectile.getTypeByName('BouncingShotgunPellet');i.shootSpeed=18;i.useAmmo=Terraria.ID.AmmoID.Bullet;i.UseSound=Terraria.ID.SoundID.Item38;i.useStyle=Terraria.ID.ItemUseStyleID.Shoot;i.autoReuse=true;i.noMelee=true;i.value=Terraria.Item.buyPrice(0,5,0,0);i.rare=Terraria.ID.ItemRarityID.Orange;this.MenuCategories.push('ranged');}
 HoldoutOffset(){return {X:-7,Y:0};}
 CanUseItem(item,player){return Ammo5(player,item.useAmmo)!=null;}
 Shoot(item,player,position,velocity,type,damage,knockBack){const a=Ammo5(player,item.useAmmo);if(!a)return false;const src=Source(player,item),owner=Terraria.PlayerIndex(player),proj=Number(ModProjectile.getTypeByName('BouncingShotgunPellet')||0);if(proj<=0)return false;const ranged=Math.max(0,N(player.rangedDamage,1)),dmg=Math.max(1,Math.floor(N(damage)+N(a.damage)*ranged)),kb=N(knockBack)+N(a.knockBack),vx=N(velocity.X),vy=N(velocity.Y),m=Math.sqrt(vx*vx+vy*vy)||1,ux=vx/m,uy=vy/m,spawn=Vector2.new(N(position.X)+ux*48,N(position.Y)+uy*48);for(let n=0;n<40;n++)NewProjectile(src,spawn,Vector2.new(vx+(Math.random()*30-15),vy+(Math.random()*30-15)),proj,dmg,kb,owner,0,0,0,null);Consume5(player,a);return false;}
 AddRecipes(){this.CreateRecipe().AddIngredient(97,100).AddRecipeGroup('IronBar',7).AddIngredient(ModItem.getTypeByName('AerialiteBar'),3).AddTile(Terraria.ID.TileID.Anvils).Register();}
}
