import { Terraria, Modules } from './../../../TL/ModImports.js';
import { ModProjectile } from './../../../TL/ModProjectile.js';
import { FusionEntityData } from './../../../Core/FusionEntityData.js';
import { PlayItemSound } from './../../../Common/Snippets/LegacySoundCompat.js';
const { Vector2, Color }=Modules;
const SpriteEffects=new NativeClass('Microsoft.Xna.Framework.Graphics','SpriteEffects');
const NewDust=Terraria.Dust['int NewDust(Vector2 Position, int Width, int Height, int Type, float SpeedX, float SpeedY, int Alpha, Color newColor, float Scale)'];
function N(v,f=0){const n=Number(v);return Number.isFinite(n)?n:f;}function I(v,f=-1){const n=Math.floor(Number(v));return Number.isFinite(n)?n:f;}
function player(o){const i=I(o);if(i<0)return null;try{if(i===I(Terraria.Main.myPlayer,-2))return Terraria.Main.LocalPlayer;}catch(_){}try{return Terraria.Main.player.get_Item(i);}catch(_){return null;}}
function center(e){try{return e.Center;}catch(_){return Vector2.Zero;}}function valid(n){try{return !!n&&n.active!==false&&n.dontTakeDamage!==true&&N(n.life)>0;}catch(_){return false;}}
function norm(v,s=1){const x=N(v?.X),y=N(v?.Y),l=Math.sqrt(x*x+y*y)||1;return Vector2.new(x/l*s,y/l*s);}function smooth(t){t=Math.max(0,Math.min(1,t));return t*t*(3-2*t);}function dust(p,id,c=1,s=1){for(let i=0;i<c;i++)try{NewDust(p.position,p.width,p.height,id,(Math.random()-.5)*4,(Math.random()-.5)*4,100,Color.White,s);}catch(_){} }

const YateveoHB=new Map();
export function YateveoBloomActive(o){const now=I(Terraria.Main.GameUpdateCount,0),t=I(YateveoHB.get(Number(o)),-9999);if(now-t<=3)return true;YateveoHB.delete(Number(o));return false;}
export class YateveoBloomMace extends ModProjectile{
 constructor(){super();this.Texture='Items/Weapons/Melee/YateveoBloom';try{this.AIType=Number(Terraria.ID.ProjectileID.BallOHurt);}catch(_){} }
 SetDefaults(){try{this.CloneDefaults(Terraria.ID.ProjectileID.BallOHurt);}catch(_){const p=this.Projectile;p.aiStyle=15;p.width=p.height=30;p.friendly=true;p.penetrate=-1;p.tileCollide=true;}const p=this.Projectile;p.width=p.height=30;p.friendly=true;p.hostile=false;p.melee=true;p.penetrate=-1;p.usesLocalNPCImmunity=true;p.localNPCHitCooldown=10;}
 AI(p){YateveoHB.set(Number(p.owner),I(Terraria.Main.GameUpdateCount,0));}
 OnHitNPC(p,n){try{n.AddBuff(Terraria.ID.BuffID.Poisoned,180,false);}catch(_){} }
 OnKill(p){YateveoHB.delete(Number(p.owner));}
}
export class YateveoBloomSpear extends ModProjectile{
 constructor(){super();this.Texture='Items/Weapons/Melee/YateveoBloom';try{this.AIType=Number(Terraria.ID.ProjectileID.Trident);}catch(_){} }
 SetDefaults(){try{this.CloneDefaults(Terraria.ID.ProjectileID.Trident);}catch(_){const p=this.Projectile;p.aiStyle=19;p.width=p.height=40;p.friendly=true;p.penetrate=-1;p.tileCollide=false;}const p=this.Projectile;p.width=p.height=40;p.friendly=true;p.hostile=false;p.melee=true;p.penetrate=-1;p.tileCollide=false;p.ignoreWater=true;p.ownerHitCheck=true;p.usesLocalNPCImmunity=true;p.localNPCHitCooldown=10;}
 AI(p){YateveoHB.set(Number(p.owner),I(Terraria.Main.GameUpdateCount,0));}
 OnHitNPC(p,n){try{n.AddBuff(Terraria.ID.BuffID.Poisoned,180,false);}catch(_){} }
 OnKill(p){YateveoHB.delete(Number(p.owner));}
}

const BladeStacks=new Map();
function removeBlade(p,st){if(!st||st.targetId===undefined)return;const a=BladeStacks.get(st.targetId);if(!a)return;const b=a.filter(x=>x&&x!==p&&x.active!==false);if(b.length)BladeStacks.set(st.targetId,b);else BladeStacks.delete(st.targetId);}
let BladecrestTexture=null;function bladecrestTex(){if(BladecrestTexture)return BladecrestTexture;try{BladecrestTexture=tl.texture.load('Textures/Items/Weapons/Melee/BladecrestOathsword.png');}catch(_){}return BladecrestTexture;}
export class BladecrestOathswordThrownBlade extends ModProjectile{
 constructor(){super();this.Texture='Items/Weapons/Melee/BladecrestOathsword';}
 SetDefaults(){const p=this.Projectile;p.width=p.height=12;p.friendly=true;p.hostile=false;p.melee=true;p.tileCollide=false;p.penetrate=-1;p.timeLeft=140;p.aiStyle=-1;p.usesLocalNPCImmunity=true;p.localNPCHitCooldown=-1;}
 OnSpawn(p){const a=norm(p.velocity);FusionEntityData.GetProjectileBag(p,'bladecrest',()=>({age:0,thrown:false,stuck:null,targetId:-1,ox:0,oy:0,stuckTime:0,ground:false,ax:N(a.X,1),ay:N(a.Y),chargeTime:19}));}
 AI(p){const pl=player(p.owner),st=FusionEntityData.GetProjectileBag(p,'bladecrest',()=>({age:0,thrown:false,stuck:null,targetId:-1,ox:0,oy:0,stuckTime:0,ground:false,ax:1,ay:0,chargeTime:19}));st.age++;if(st.stuck&&valid(st.stuck)){const c=center(st.stuck);p.Center=Vector2.new(N(c.X)+N(st.ox),N(c.Y)+N(st.oy));p.velocity=Vector2.Zero;p.friendly=false;p.tileCollide=false;st.stuckTime++;if(st.stuckTime>=180)this.Release(p,st);}else if(st.stuck){this.Release(p,st);}if(st.ground){p.velocity=Vector2.Zero;p.friendly=false;p.tileCollide=false;p.rotation+=.01;return;}if(!st.thrown){if(!pl||pl.active===false||pl.dead===true){p.Kill();return;}let a=norm(Vector2.new(N(st.ax,1),N(st.ay)));try{const c=pl.MountedCenter,m=Terraria.Main.MouseWorld;a=norm(Vector2.new(N(m.X)-N(c.X),N(m.Y)-N(c.Y)));}catch(_){}st.ax=N(a.X);st.ay=N(a.Y);const dir=N(a.X)>=0?1:-1;const grav=N(pl.gravDir,1);const useTime=Math.max(1,I(N(pl?.HeldItem?.useTime,53),53));st.chargeTime=Math.max(1,Math.min(100,Math.floor(useTime/2.8)||19));const progress=Math.max(0,Math.min(1,st.age/Math.max(1,st.chargeTime)));let baseArm=0;const pullEnd=-Math.PI/4*1.2;if(progress<0.7){const t=Math.max(0,Math.min(1,progress/0.7));const eased=1-Math.pow(1-t,2);baseArm=pullEnd*eased;}else{const t=Math.max(0,Math.min(1,(progress-0.7)/0.3));const eased=1-Math.pow(1-t,3);baseArm=pullEnd+eased*(Math.PI/4*1.2+Math.PI/2);}const armRotation=baseArm*dir;const handReach=-12*grav*N(p.scale,1);const offX=(-Math.sin(armRotation*grav))*handReach,offY=(Math.cos(armRotation*grav))*handReach;p.velocity=Vector2.Zero;p.Center=Vector2.new(N(pl.MountedCenter.X)+offX,N(pl.MountedCenter.Y)+offY);p.rotation=(-Math.PI/4*dir+armRotation)*grav;p.direction=p.spriteDirection=dir;try{Terraria.SetPlayerDirection(pl,dir);}catch(_){}try{pl.heldProj=p.whoAmI;pl.SetCompositeArmFront(true,Terraria.Player.CompositeArmStretchAmount.Full,Math.PI+armRotation);}catch(_){}if(st.age>=st.chargeTime){st.thrown=true;p.Center=Vector2.new(N(pl.MountedCenter.X)+N(a.X)*12*N(p.scale,1),N(pl.MountedCenter.Y)+N(a.Y)*12*N(p.scale,1));p.velocity=norm(a,14);p.direction=p.spriteDirection=dir;p.rotation=Math.atan2(N(p.velocity.Y),N(p.velocity.X))+(dir>0?Math.PI/4:Math.PI*3/4);p.tileCollide=true;p.timeLeft=100;p.netUpdate=true;try{PlayItemSound(1,p.Center,-.15,.3);}catch(_){}}return;}if(!st.stuck){const dir=N(p.velocity.X)>=0?1:-1;p.direction=p.spriteDirection=dir;p.rotation=Math.atan2(N(p.velocity.Y),N(p.velocity.X))+(dir>0?Math.PI/4:Math.PI*3/4);if(st.age>52)p.velocity=Vector2.new(N(p.velocity.X)*.99,N(p.velocity.Y)+.06);}}
 CanDamage(p){const st=FusionEntityData.GetProjectileBag(p,'bladecrest',()=>({thrown:false,stuck:null,ground:false}));return st.thrown&&!st.stuck&&!st.ground?null:false;}
 OnHitNPC(p,n){if(!valid(n))return;const st=FusionEntityData.GetProjectileBag(p,'bladecrest',()=>({stuck:null,targetId:-1,ox:0,oy:0,stuckTime:0})),nc=center(n),pc=center(p),id=I(n.whoAmI,-1);st.stuck=n;st.targetId=id;st.ox=N(pc.X)-N(nc.X);st.oy=N(pc.Y)-N(nc.Y);st.stuckTime=0;p.velocity=Vector2.Zero;p.friendly=false;p.tileCollide=false;let a=BladeStacks.get(id)||[];a=a.filter(x=>x&&x.active!==false);a.push(p);while(a.length>3){const old=a.shift();if(old&&old!==p)try{old.Kill();}catch(_){old.active=false;}}BladeStacks.set(id,a);dust(p,5,5,.9);}
 Release(p,st){removeBlade(p,st);st.stuck=null;st.targetId=-1;st.stuckTime=0;p.friendly=true;p.tileCollide=true;p.velocity=Vector2.new((Math.random()-.5)*5,-3-Math.random()*2);p.timeLeft=Math.min(I(p.timeLeft,60),60);}
 OnTileCollide(p,old){const st=FusionEntityData.GetProjectileBag(p,'bladecrest',()=>({ground:false}));st.ground=true;p.velocity=Vector2.Zero;p.friendly=false;p.tileCollide=false;p.timeLeft=Math.min(I(p.timeLeft,60),60);return false;}
 PreDraw(p,lightColor){const st=FusionEntityData.GetProjectileBag(p,'bladecrest',()=>({thrown:false,ground:false,stuck:null}));if(st.thrown||st.ground||st.stuck)return true;const tex=bladecrestTex();if(!tex)return true;try{const draw=Terraria.Main.spriteBatch['void Draw(Texture2D texture, Vector2 position, Nullable`1 sourceRectangle, Color color, float rotation, Vector2 origin, float scale, SpriteEffects effects, float layerDepth)'];if(!draw)return true;const dir=I(p.spriteDirection,1)<0?-1:1,pos=Vector2.new(N(p.Center.X)-N(Terraria.Main.screenPosition.X),N(p.Center.Y)-N(Terraria.Main.screenPosition.Y)+N(p.gfxOffY)),gripX=8,gripY=46,origin=dir<0?Vector2.new(N(tex.Width)-gripX,gripY):Vector2.new(gripX,gripY),fx=dir<0?SpriteEffects.FlipHorizontally:SpriteEffects.None;draw(tex,pos,null,lightColor,N(p.rotation),origin,N(p.scale,1),fx,0);return false;}catch(_){return true;}}
 OnKill(p){const st=FusionEntityData.GetProjectileBag(p,'bladecrest',()=>({targetId:-1}));removeBlade(p,st);}
}

const OldLordHB=new Map(),OldLordAim=new Map(),OldLordParity=new Map();
export function RegisterOldLordAim(o,a){OldLordAim.set(Number(o),norm(a));}
export function OldLordClaymoreActive(o){const now=I(Terraria.Main.GameUpdateCount,0),t=I(OldLordHB.get(Number(o)),-9999);if(now-t<=3)return true;OldLordHB.delete(Number(o));return false;}
let OldLordTexture=null;function oldLordTex(){if(OldLordTexture)return OldLordTexture;try{OldLordTexture=tl.texture.load('Textures/Items/Weapons/Melee/OldLordClaymore.png');}catch(_){}return OldLordTexture;}
export class OldLordClaymoreHoldout extends ModProjectile{
 constructor(){super();this.Texture='Items/Weapons/Melee/OldLordClaymore';}
 SetDefaults(){const p=this.Projectile;p.width=p.height=120;p.friendly=true;p.hostile=false;p.melee=true;p.penetrate=-1;p.timeLeft=100;p.tileCollide=false;p.ignoreWater=true;p.scale=1.2;p.aiStyle=-1;p.usesLocalNPCImmunity=true;p.localNPCHitCooldown=-1;}
 OnSpawn(p){const key=Number(p.owner),parity=I(OldLordParity.get(key),0)&1;OldLordParity.set(key,parity^1);FusionEntityData.GetProjectileBag(p,'oldLord',()=>({age:0,parity,baseDamage:Math.max(1,I(p.damage,100)),hits:0}));OldLordHB.set(key,I(Terraria.Main.GameUpdateCount,0));}
 AI(p){const pl=player(p.owner),st=FusionEntityData.GetProjectileBag(p,'oldLord',()=>({age:0,parity:0,baseDamage:Math.max(1,I(p.damage,100)),hits:0}));if(!pl||pl.active===false||pl.dead===true){p.Kill();return;}st.age++;if(st.age>90){p.Kill();return;}OldLordHB.set(Number(p.owner),I(Terraria.Main.GameUpdateCount,0));let a=OldLordAim.get(Number(p.owner))||norm(p.velocity);try{if(I(p.owner)===I(Terraria.Main.myPlayer)){const m=Terraria.Main.MouseWorld,c=pl.MountedCenter,dx=N(m.X)-N(c.X),dy=N(m.Y)-N(c.Y);if(dx*dx+dy*dy>4)a=norm(Vector2.new(dx,dy));}}catch(_){}OldLordAim.set(Number(p.owner),a);const dir=N(a.X)>=0?1:-1,base=Math.atan2(N(a.Y),N(a.X)),progress=smooth((st.age-1)/89),sign=I(st.parity,0)===0?1:-1,relative=(-2.1+4.2*progress)*sign*dir,angle=base+relative,blade=Vector2.new(Math.cos(angle),Math.sin(angle));try{Terraria.SetPlayerDirection(pl,dir);}catch(_){}p.direction=p.spriteDirection=dir;p.Center=Vector2.new(N(pl.MountedCenter.X)+N(blade.X)*12,N(pl.MountedCenter.Y)+N(blade.Y)*12);p.velocity=blade;p.rotation=angle;p.timeLeft=100;try{pl.heldProj=p.whoAmI;pl.itemTime=2;pl.itemAnimation=2;const grav=N(pl.gravDir,1),arm=(angle-Math.PI/2)*grav+(grav<0?Math.PI:0);pl.SetCompositeArmFront(true,Terraria.Player.CompositeArmStretchAmount.Full,arm);}catch(_){} }
 CanDamage(p){const st=FusionEntityData.GetProjectileBag(p,'oldLord',()=>({age:0}));return st.age>=30&&st.age<=76?null:false;}
 OnHitNPC(p,n){const st=FusionEntityData.GetProjectileBag(p,'oldLord',()=>({hits:0,baseDamage:Math.max(1,I(p.damage,100))}));try{n.AddBuff(Terraria.ID.BuffID.OnFire3,180,false);}catch(_){try{n.AddBuff(Terraria.ID.BuffID.OnFire,180,false);}catch(__){}}const a=OldLordAim.get(Number(p.owner))||norm(p.velocity);try{n.velocity=Vector2.new(N(a.X)*12,N(a.Y)*12);}catch(_){}st.hits++;p.damage=Math.max(1,Math.floor(I(st.baseDamage,100)*Math.max(.3,1-st.hits*.1)));dust(p,6,Math.max(3,10-st.hits),1.15);try{PlayItemSound(1,p.Center,-.35,.35);}catch(_){} }
 PreDraw(p,lightColor){const tex=oldLordTex();if(!tex)return true;try{const draw=Terraria.Main.spriteBatch['void Draw(Texture2D texture, Vector2 position, Nullable`1 sourceRectangle, Color color, float rotation, Vector2 origin, float scale, SpriteEffects effects, float layerDepth)'];if(!draw)return true;const dir=I(p.spriteDirection,1)<0?-1:1,pos=Vector2.new(N(p.Center.X)-N(Terraria.Main.screenPosition.X),N(p.Center.Y)-N(Terraria.Main.screenPosition.Y)+N(p.gfxOffY)),origin=dir<0?Vector2.new(N(tex.Width),N(tex.Height)):Vector2.new(0,N(tex.Height)),rot=N(p.rotation)+(dir<0?Math.PI-Math.PI/4:Math.PI/4),fx=dir<0?SpriteEffects.FlipHorizontally:SpriteEffects.None;draw(tex,pos,null,lightColor,rot,origin,N(p.scale,1.2),fx,0);return false;}catch(_){return true;}}
 OnKill(p){OldLordHB.delete(Number(p.owner));OldLordAim.delete(Number(p.owner));}
}
