import { Terraria, Modules } from './../../../TL/ModImports.js';
import { ModProjectile } from './../../../TL/ModProjectile.js';
import { AndroidSound } from './../../../Common/Snippets/AndroidSound.js';
import { RoxcaliburSignal, ClearRoxcaliburSignal } from './../../../Core/RoxcaliburSignalRuntime.js';
const { Vector2 }=Modules;const NewProjectile=Terraria.Projectile['int NewProjectile(IEntitySource spawnSource, Vector2 position, Vector2 velocity, int Type, int Damage, float KnockBack, int Owner, float ai0, float ai1, float ai2, NewProjectileModifier modifer)'];
const PI=Math.PI;function N(v,f=0){const n=Number(v);return Number.isFinite(n)?n:f;}function Clamp(v,a,b){return Math.max(a,Math.min(b,v));}function Center(p){try{return p.Center;}catch(e){return Vector2.new(N(p.position?.X)+N(p.width)/2,N(p.position?.Y)+N(p.height)/2);}}function SetCenter(p,x,y){p.position.X=x-N(p.width)/2;p.position.Y=y-N(p.height)/2;}function Source(){try{return null;}catch(e){return null;}}function Norm(x,y){const d=Math.sqrt(x*x+y*y)||1;return {x:x/d,y:y/d};}
function DustBurst(p){const c=Center(p);for(let i=0;i<24;i++){const a=2*PI*i/24,dx=Math.cos(a),dy=Math.sin(a);try{const d=Terraria.Dust['int NewDust(Vector2 Position, int Width, int Height, int Type, float SpeedX, float SpeedY, int Alpha, Color newColor, float Scale)'](Vector2.new(N(c.X)+dx*20*N(p.scale,1),N(c.Y)+dy*20*N(p.scale,1)),0,0,1,dx*12*N(p.scale,1),dy*12*N(p.scale,1),0,null,N(p.scale,1));}catch(e){}}}
function PlayVanilla(type,style,p,pitch=0){try{Terraria.Audio.SoundEngine['void PlaySound(int type, Vector2 position, int style, float pitchOffset)'](type,Center(p),style,pitch);}catch(e){}}
class RoxShardBase extends ModProjectile{
 SetDefaults(){const p=this.Projectile;p.width=20;p.height=20;p.friendly=true;p.melee=true;p.extraUpdates=1;p.timeLeft=300;p.penetrate=1;}
 AI(p){p.velocity.Y=N(p.velocity.Y)+0.13;if(N(p.velocity.Y)>16)p.velocity.Y=16;p.rotation=Math.atan2(N(p.velocity.Y),N(p.velocity.X))+PI/2;p.spriteDirection=p.direction=N(p.velocity.X)<0?-1:1;if(Math.random()<0.1)try{Terraria.Dust['int NewDust(Vector2 Position, int Width, int Height, int Type, float SpeedX, float SpeedY, int Alpha, Color newColor, float Scale)'](p.position,p.width,p.height,191,N(p.velocity.X)*0.4,N(p.velocity.Y)*0.4,160,null,0.7);}catch(e){}}
 OnTileCollide(p){for(let i=0;i<8;i++)try{Terraria.Dust['int NewDust(Vector2 Position, int Width, int Height, int Type, float SpeedX, float SpeedY, int Alpha, Color newColor, float Scale)'](p.position,p.width,p.height,191,-N(p.velocity.X)*0.4,-N(p.velocity.Y)*0.4,120,null,1.2);}catch(e){}PlayVanilla(0,1,p,0);p.active=false;return false;}
}
export class Rox1 extends RoxShardBase{constructor(){super();this.Texture='Projectiles/Melee/Rox1';}}
export class Rox2 extends RoxShardBase{constructor(){super();this.Texture='Projectiles/Melee/Rox2';}}
export class Rox3 extends RoxShardBase{constructor(){super();this.Texture='Projectiles/Melee/Rox3';}}
export class RoxcaliburProj extends ModProjectile{
 constructor(){super();this.Texture='Items/Weapons/Melee/Roxcalibur';this.States=new Map();this.RoxTypes=[];}
 SetDefaults(){const p=this.Projectile;p.penetrate=-1;p.width=100;p.height=100;p.melee=true;p.friendly=true;p.tileCollide=false;p.scale=1.3;p.timeLeft=3600;p.usesLocalNPCImmunity=true;p.localNPCHitCooldown=150;p.aiStyle=-1;}
 K(p){return Math.floor(N(p.whoAmI,-1));}S(p,player){const k=this.K(p);let s=this.States.get(k);if(!s){s={charge:0,hit:0,anim:0,rot:0,dir:Number(Terraria.PlayerDirection(player))||1,charged:false,orig:Math.max(1,Math.floor(N(RoxcaliburSignal(p.owner).itemTimeMax,40))),baseDamage:Math.max(1,Math.floor(N(p.damage,180))),released:false,logged:false};this.States.set(k,s);}return s;}
 Aim(owner,player,p){const sig=RoxcaliburSignal(owner),pc=Terraria.PlayerCenter(player);let x=N(sig.aimX,N(pc.X)+(Number(Terraria.PlayerDirection(player))||1)*100),y=N(sig.aimY,N(pc.Y));if(sig.ageMs>1000){const v=p.velocity;x=N(pc.X)+N(v.X,1)*100;y=N(pc.Y)+N(v.Y)*100;}return {x,y,pc};}
 RockOffset(p){const len=Math.sqrt(N(p.width)*N(p.width)+N(p.height)*N(p.height));return {x:N(p.velocity.X)*.25*len,y:N(p.velocity.Y)*.25*len};}
 CanDamage(p){const s=this.States.get(this.K(p));return !!s&&s.anim!==0&&s.hit<5;}
 ModifyDamageHitbox(p,h){const s=this.States.get(this.K(p));if(!s||!(s.hit>0&&s.hit<5))return;const m=2+1.5*s.charge,c=Center(p),o=this.RockOffset(p),w=N(p.width)*m,hh=N(p.height)*m;h.X=Math.floor(N(c.X)+o.x-w/2);h.Y=Math.floor(N(c.Y)+o.y-hh/2);h.Width=Math.floor(w);h.Height=Math.floor(hh);}
 Release(p,s,player,aim){s.anim=aim.y>N(aim.pc.Y)?2:1;s.released=true;let m=s.charge*2.5;if(s.anim===2){p.timeLeft=120;m=s.charge*3.5;}p.damage=Math.max(1,Math.floor(s.baseDamage*(1+m)));AndroidSound.PlayOneShot('Sounds/Custom/LoudSwingWoosh.ogg',0.75,N(Center(p).X),N(Center(p).Y),1400,120);try{tl.log(`[CalamityPort Roxcalibur] released; mode=${s.anim===2?'plunge':'swing'}, charge=${s.charge.toFixed(3)}, damage=${p.damage}.`);}catch(e){}}
 Collision(p,s,player){if(s.hit!==0)return;s.hit=1;PlayVanilla(2,14,p,0);if(s.anim===2)try{player.velocity.Y=-N(player.gravDir,1)*20*(s.charge+1)/2;}catch(e){}s.anim=3;DustBurst(p);try{tl.log(`[CalamityPort Roxcalibur] collision shockwave; charge=${s.charge.toFixed(3)}.`);}catch(e){}}
 SpawnShard(p,s,player){if(Number(Terraria.Main.myPlayer)!==Number(p.owner))return;if(!this.RoxTypes.length)this.RoxTypes=[ModProjectile.getTypeByName('Rox1'),ModProjectile.getTypeByName('Rox2'),ModProjectile.getTypeByName('Rox3')].map(Number).filter(x=>x>0);if(!this.RoxTypes.length)return;const o=this.RockOffset(p),c=Center(p),a=(Math.random()-.5)*(20*PI/180),vx=N(p.velocity.X)*8,vy=N(p.velocity.Y)*8,ca=Math.cos(a),sa=Math.sin(a),type=this.RoxTypes[Math.floor(Math.random()*this.RoxTypes.length)];NewProjectile(Source(),Vector2.new(N(c.X)+o.x,N(c.Y)+o.y),Vector2.new(vx*ca-vy*sa,vx*sa+vy*ca),type,Math.max(1,Math.floor(N(p.damage)*.4)),1,p.owner,0,0,0,null);}
 AI(p){const sig=RoxcaliburSignal(p.owner),player=sig.player;if(!player||player.dead===true){p.active=false;this.States.delete(this.K(p));return;}const s=this.S(p,player),aim=this.Aim(p.owner,player,p),grav=N(player.gravDir,1)||1;try{player.heldProj=p.whoAmI;}catch(e){}const hold=Math.sqrt(N(p.width)*N(p.width)+N(p.height)*N(p.height))/2,chargeTime=s.orig/40*120;
   if(player.channel===true&&!s.released)s.anim=0;else if(s.anim===0&&!s.released)this.Release(p,s,player,aim);
   if(s.anim===0){s.charge=Math.min(1,s.charge+1/Math.max(1,chargeTime));let dir=aim.x<N(aim.pc.X)?-1:1;s.dir=dir;const t=Math.pow(s.charge,.4),smooth=t*t*(3-2*t);s.rot=(-PI/8+(PI/3+PI/8)*smooth)*(-dir);p.timeLeft=s.orig;if(s.charge>=1&&!s.charged){s.charged=true;PlayVanilla(3,42,p,.4);try{tl.log('[CalamityPort Roxcalibur] fully charged.');}catch(e){}}}
   else if(s.anim===1){if(N(p.timeLeft)>s.orig)p.timeLeft=s.orig;const progress=N(p.timeLeft)/s.orig,cm=(s.charge+1)/2;let am=Clamp(progress,0,1);if(am>.5)am=1-am;am=am*am+.02;s.rot+=s.dir*am*cm*2*PI*.2;p.localNPCHitCooldown=Math.ceil(s.orig);const timer=s.charge>=.95?2:(s.charge>=.5?4:6);if(progress<.8&&progress>.2&&Math.floor(N(p.timeLeft))%timer===0)this.SpawnShard(p,s,player);}
   else if(s.anim===2){const speed=20*(s.charge+1)/2,down=grav*speed;let collided=false;try{const rect=Terraria.PlayerRect(player),next=Vector2.new(N(rect.X),N(rect.Y)+down);collided=!!Terraria.Collision['bool SolidCollision(Vector2 Position, int Width, int Height)'](next,N(rect.Width),N(rect.Height));}catch(e){}if(collided)this.Collision(p,s,player);else{try{player.position.Y=N(player.position.Y)+down;player.velocity.X=N(player.velocity.X)*.95;player.velocity.Y=0;}catch(e){}const ad=Math.atan2(grav,N(p.velocity.X)||s.dir)-Math.atan2(N(p.velocity.Y),N(p.velocity.X));const d=Math.abs(ad)>PI/2?s.dir:(ad<0?-1:1);s.rot+=d*Math.abs(ad)*.12*((s.charge+1)/2);p.localNPCHitCooldown=Math.ceil(s.orig);}}
   else if(s.anim===3){if(N(p.timeLeft)>s.orig/3)p.timeLeft=Math.floor(s.orig/3);const m=Clamp(N(p.timeLeft)/s.orig,0,1);s.rot-=s.dir*m*2*PI*2/s.orig;}
   if(s.hit>0&&s.hit<=5)s.hit++;
   const vx=Math.sin(s.rot)*grav,vy=-Math.cos(s.rot)*grav;p.velocity.X=vx;p.velocity.Y=vy;const pc=Terraria.PlayerCenter(player);SetCenter(p,N(pc.X)+vx*hold,N(pc.Y)+vy*hold);p.rotation=Math.atan2(vy,vx);p.spriteDirection=p.direction=s.dir;try{Terraria.SetPlayerDirection(player,s.dir);player.itemRotation=Math.atan2(vy*s.dir,vx*s.dir);player.itemTime=Math.max(N(player.itemTime),2);player.itemAnimation=Math.max(N(player.itemAnimation),2);}catch(e){}p.rotation+=s.dir===-1?(-PI/4+PI):(-3*PI/4+PI);}
 OnHitNPC(p,npc){const s=this.States.get(this.K(p)),sig=RoxcaliburSignal(p.owner);if(!s||!sig.player)return;this.Collision(p,s,sig.player);p.damage=Math.max(1,Math.floor(N(p.damage)*.75));}
 OnKill(p){this.States.delete(this.K(p));ClearRoxcaliburSignal(p.owner);}
}
