import { Terraria, Modules } from './../../../TL/ModImports.js';
import { ModProjectile } from './../../../TL/ModProjectile.js';
import { FusionEntityData } from './../../../Core/FusionEntityData.js';
import { MarkRogueProjectile, IsStealthStrike } from './../../../Core/RogueRuntime.js';
import { ScanFrozenCubeNPCs, FrozenCubeTrackedIndices, FrozenCubeNPC } from './../../../Core/FrozenCubeTargetRuntime.js';
const { Vector2, Color }=Modules;
const NewProjectile=Terraria.Projectile['int NewProjectile(IEntitySource spawnSource, Vector2 position, Vector2 velocity, int Type, int Damage, float KnockBack, int Owner, float ai0, float ai1, float ai2, NewProjectileModifier modifer)'];
const NewDust=Terraria.Dust['int NewDust(Vector2 Position, int Width, int Height, int Type, float SpeedX, float SpeedY, int Alpha, Color newColor, float Scale)'];
function N(v,f=0){const n=Number(v);return Number.isFinite(n)?n:f;}function center(e){try{return e.Center;}catch(_){return Vector2.new(N(e.position.X)+N(e.width)*.5,N(e.position.Y)+N(e.height)*.5);}}function owner(p){try{return Terraria.Main.player[Math.floor(N(p.owner,-1))];}catch(_){return null;}}function norm(v,fx=1,fy=0){const x=N(v&&v.X),y=N(v&&v.Y),d=Math.sqrt(x*x+y*y);return d>.001?Vector2.new(x/d,y/d):Vector2.new(fx,fy);}function toward(a,b,s){return Vector2.Multiply(norm(Vector2.new(N(b.X)-N(a.X),N(b.Y)-N(a.Y))),s);}function valid(n,p){try{return !!n&&n.active&&!n.friendly&&!n.townNPC&&!n.dontTakeDamage&&N(n.life)>0&&n.CanBeChasedBy(p,false);}catch(_){return false;}}
function target(p,range,exclude){ScanFrozenCubeNPCs(2);const pc=center(p);let best=null,bd=range;for(const i of FrozenCubeTrackedIndices()){const n=FrozenCubeNPC(i);if(!valid(n,p))continue;const id=Math.floor(N(n.whoAmI,-1));if(exclude&&exclude.has(id))continue;const nc=center(n),dx=N(nc.X)-N(pc.X),dy=N(nc.Y)-N(pc.Y),d=Math.sqrt(dx*dx+dy*dy);if(d<bd){bd=d;best=n;}}return best;}
function dust(p,type,count=3){for(let i=0;i<count;i++)try{NewDust(p.position,p.width,p.height,type,(Math.random()-.5)*2,(Math.random()-.5)*2,80,Color.White,.9);}catch(_){} }
class HeavyAxeBase extends ModProjectile{SetDefaults(){const p=this.Projectile;p.width=30;p.height=30;p.friendly=true;p.penetrate=2;p.timeLeft=600;p.usesLocalNPCImmunity=true;p.localNPCHitCooldown=10;p.aiStyle=-1;}OnSpawn(p){MarkRogueProjectile(p,this.SourceName,false);FusionEntityData.GetProjectileBag(p,'heavyAxe',()=>({age:0,boosted:false}));}AI(p){const s=FusionEntityData.GetProjectileBag(p,'heavyAxe',()=>({age:0,boosted:false}));s.age++;p.rotation=N(p.rotation)+(Math.abs(N(p.velocity.X))+Math.abs(N(p.velocity.Y)))*.019*(N(p.velocity.X)>=0?1:-1);p.velocity=Vector2.new(N(p.velocity.X),Math.min(16,N(p.velocity.Y)+.2));if(s.age===1&&!s.boosted){p.damage=Math.max(1,Math.floor(N(p.damage)*2));s.boosted=true;}if(s.age===15&&s.boosted){p.damage=Math.max(1,Math.floor(N(p.damage)/2));s.boosted=false;}}OnTileCollide(){return true;}OnKill(p){dust(p,1,4);}}
export class IronFranciscaProj extends HeavyAxeBase{constructor(){super();this.Texture='Items/Weapons/Rogue/IronFrancisca';this.SourceName='IronFrancisca';}}
export class LeadTomahawkProj extends HeavyAxeBase{constructor(){super();this.Texture='Items/Weapons/Rogue/LeadTomahawk';this.SourceName='LeadTomahawk';}}

export class EnchantedAxeProj extends ModProjectile{
 constructor(){super();this.Texture='Items/Weapons/Rogue/EnchantedAxe';}
 SetDefaults(){const p=this.Projectile;p.width=10;p.height=10;p.friendly=true;p.penetrate=-1;p.timeLeft=600;p.usesLocalNPCImmunity=true;p.localNPCHitCooldown=15;p.aiStyle=-1;}
 OnSpawn(p){MarkRogueProjectile(p,'EnchantedAxe',false);FusionEntityData.GetProjectileBag(p,'enchAxe',()=>({age:0,recall:false,spawnedRecall:false,childTick:0}));}
 AI(p){const s=FusionEntityData.GetProjectileBag(p,'enchAxe',()=>({age:0,recall:false,spawnedRecall:false,childTick:0})),pl=owner(p);if(!pl||pl.dead){p.Kill();return;}s.age++;p.rotation=N(p.rotation)+.4*(N(p.velocity.X)>=0?1:-1);const trigger=IsStealthStrike(p)?18:10;if(!s.recall&&s.age>=trigger){s.recall=true;p.tileCollide=false;}
  if(IsStealthStrike(p)&&!s.recall&&s.age%3===1&&s.age<=16)this.SpawnChild(p,true);
  if(s.recall){if(!s.spawnedRecall){s.spawnedRecall=true;this.SpawnChild(p,false);}const pc=Terraria.PlayerCenter(pl),cc=center(p),dx=N(pc.X)-N(cc.X),dy=N(pc.Y)-N(cc.Y),d=Math.sqrt(dx*dx+dy*dy);if(d<30){p.Kill();return;}p.velocity=toward(cc,pc,30);p.tileCollide=false;}
 }
 SpawnChild(p,home){const t=Number(ModProjectile.getTypeByName('EnchantedAxe2')||0);if(!(t>0))return;let n=target(p,999,null),v=n?toward(center(p),center(n),20):Vector2.Multiply(p.velocity,-1);const id=NewProjectile(p.GetProjectileSource_FromThis(),center(p),v,t,Math.max(1,N(p.damage)),2,p.owner,0,0,0,null);try{const q=Terraria.Main.projectile[id];if(q){MarkRogueProjectile(q,'EnchantedAxe',true);const b=FusionEntityData.GetProjectileBag(q,'enchAxe2',()=>({age:0,target:-1,home:false}));b.home=!!home;}}catch(_){} }
 OnTileCollide(p){const s=FusionEntityData.GetProjectileBag(p,'enchAxe',()=>({age:0,recall:false,spawnedRecall:false,childTick:0}));s.recall=true;p.tileCollide=false;return false;}
}
export class EnchantedAxe2 extends ModProjectile{
 constructor(){super();this.Texture='Items/Weapons/Rogue/EnchantedAxe';}
 SetDefaults(){const p=this.Projectile;p.width=10;p.height=10;p.friendly=true;p.tileCollide=false;p.timeLeft=90;p.penetrate=1;p.usesLocalNPCImmunity=true;p.localNPCHitCooldown=-1;p.aiStyle=-1;}
 OnSpawn(p){MarkRogueProjectile(p,'EnchantedAxe',true);FusionEntityData.GetProjectileBag(p,'enchAxe2',()=>({age:0,target:-1,home:false}));}
 AI(p){const s=FusionEntityData.GetProjectileBag(p,'enchAxe2',()=>({age:0,target:-1,home:false}));s.age++;p.rotation=N(p.rotation)+.4*(N(p.velocity.X)>=0?1:-1);if(s.home){if(s.age%8===1){const n=target(p,256,null);s.target=n?Math.floor(N(n.whoAmI,-1)):-1;}if(s.target>=0){const n=FrozenCubeNPC(s.target);if(valid(n,p)){const desired=toward(center(p),center(n),15);p.velocity=Vector2.Divide(Vector2.Add(Vector2.Multiply(p.velocity,19),desired),20);}}}}
}

const FishboneCounts=new Map();export function FishboneActiveCount(o){return Number(FishboneCounts.get(Number(o))||0);}function fishInc(o,d){const k=Number(o),n=Math.max(0,FishboneActiveCount(k)+d);if(n)FishboneCounts.set(k,n);else FishboneCounts.delete(k);}
export class FishboneBoomerangProjectile extends ModProjectile{
 constructor(){super();this.Texture='Items/Weapons/Rogue/FishboneBoomerang';}
 SetDefaults(){const p=this.Projectile;p.width=38;p.height=32;p.friendly=true;p.tileCollide=false;p.penetrate=-1;p.timeLeft=250;p.ignoreWater=true;p.aiStyle=-1;}
 OnSpawn(p){MarkRogueProjectile(p,'FishboneBoomerang',false);fishInc(p.owner,1);FusionEntityData.GetProjectileBag(p,'fishbone',()=>({age:0,aim:norm(p.velocity),returning:false,hits:0,seen:new Set()}));p.velocity=Vector2.Zero;}
 AI(p){const s=FusionEntityData.GetProjectileBag(p,'fishbone',()=>({age:0,aim:Vector2.new(1,0),returning:false,hits:0,seen:new Set()})),pl=owner(p);if(!pl||pl.dead){p.Kill();return;}s.age++;const pc=Terraria.PlayerCenter(pl);if(s.age<=10){p.Center=Vector2.Add(pc,Vector2.Multiply(s.aim,34));p.rotation=Math.atan2(N(s.aim.Y),N(s.aim.X))+Math.PI/2;p.tileCollide=false;pl.heldProj=p.whoAmI;pl.itemTime=2;pl.itemAnimation=2;if(s.age===10){p.velocity=Vector2.Multiply(s.aim,17.5);p.tileCollide=true;}return;}
  p.rotation=N(p.rotation)+(.2+.18*Math.min(1,(s.age-10)/60))*(N(p.velocity.X)>=0?1:-1);const sp=Math.sqrt(N(p.velocity.X)**2+N(p.velocity.Y)**2);if(!s.returning&&s.age>45)p.velocity=Vector2.Multiply(p.velocity,.88);if(!s.returning&&sp<2)s.returning=true;if(s.returning){p.tileCollide=false;const cc=center(p),dx=N(pc.X)-N(cc.X),dy=N(pc.Y)-N(cc.Y),d=Math.sqrt(dx*dx+dy*dy);if(d<24){p.Kill();return;}const cur=Math.min(20,Math.max(6,sp*1.1));p.velocity=toward(cc,pc,cur);} }
 OnHitNPC(p,npc){const s=FusionEntityData.GetProjectileBag(p,'fishbone',()=>({age:0,aim:Vector2.new(1,0),returning:false,hits:0,seen:new Set()}));s.hits++;s.seen.add(Math.floor(N(npc.whoAmI,-1)));if(IsStealthStrike(p))this.SpawnShards(p);if(s.hits>=3){s.returning=true;p.velocity=Vector2.Multiply(p.velocity,.3);return;}const n=target(p,400,s.seen);if(n){p.velocity=toward(center(p),center(n),15);}else{s.returning=true;p.velocity=Vector2.Multiply(p.velocity,.3);}}
 SpawnShards(p){const t=Number(ModProjectile.getTypeByName('FishboneShard')||0);if(!(t>0))return;for(let i=0;i<3;i++){const a=Math.random()*Math.PI*2,s=7+Math.random()*3,v=Vector2.new(Math.cos(a)*s,Math.sin(a)*s),id=NewProjectile(p.GetProjectileSource_FromThis(),center(p),v,t,Math.max(1,Math.floor(N(p.damage)*.5)),N(p.knockBack)*.5,p.owner,0,0,0,null);try{const q=Terraria.Main.projectile[id];if(q)MarkRogueProjectile(q,'FishboneBoomerang',true);}catch(_){}}}
 OnTileCollide(p){const s=FusionEntityData.GetProjectileBag(p,'fishbone',()=>({age:0,aim:Vector2.new(1,0),returning:false,hits:0,seen:new Set()}));s.returning=true;p.velocity=Vector2.Multiply(p.velocity,-.3);p.tileCollide=false;return false;}
 OnKill(p){fishInc(p.owner,-1);}
}
export class FishboneShard extends ModProjectile{constructor(){super();this.Texture='Items/Weapons/Rogue/FishboneBoomerang';}SetDefaults(){const p=this.Projectile;p.width=10;p.height=10;p.friendly=true;p.tileCollide=true;p.penetrate=1;p.timeLeft=45;p.aiStyle=-1;p.scale=.55;}OnSpawn(p){MarkRogueProjectile(p,'FishboneBoomerang',true);}AI(p){p.rotation=N(p.rotation)+.35;p.velocity=Vector2.new(N(p.velocity.X)*.99,Math.min(12,N(p.velocity.Y)+.18));}OnTileCollide(){return true;}}

export class AshenStalactiteProj extends ModProjectile{constructor(){super();this.Texture='Items/Weapons/Rogue/AshenStalactite';}SetDefaults(){const p=this.Projectile;p.width=10;p.height=10;p.friendly=true;p.penetrate=1;p.timeLeft=25;p.aiStyle=-1;}OnSpawn(p){MarkRogueProjectile(p,'AshenStalactite',false);}AI(p){p.rotation=Math.atan2(N(p.velocity.Y),N(p.velocity.X))+Math.PI/4;p.velocity=Vector2.new(N(p.velocity.X),Math.min(16,N(p.velocity.Y)+.1));}OnTileCollide(){return true;}OnKill(p){dust(p,1,5);}}
export class AshenStalagmiteProj extends ModProjectile{constructor(){super();this.Texture='Items/Weapons/Rogue/AshenStalactite';}SetDefaults(){const p=this.Projectile;p.width=10;p.height=10;p.friendly=true;p.penetrate=2;p.timeLeft=100;p.usesIDStaticNPCImmunity=true;p.idStaticNPCHitCooldown=10;p.aiStyle=-1;}OnSpawn(p){MarkRogueProjectile(p,'AshenStalactite',false);}AI(p){p.rotation=Math.atan2(N(p.velocity.Y),N(p.velocity.X))+2.355;p.velocity=Vector2.new(N(p.velocity.X),Math.min(16,N(p.velocity.Y)+.075));}OnTileCollide(){return true;}OnKill(p){const t=Number(ModProjectile.getTypeByName('AshenStalactiteDebris')||0);if(!(t>0))return;for(let i=0;i<6;i++){const a=Math.random()*Math.PI*2,s=2+Math.random()*4,v=Vector2.new(Math.cos(a)*s,Math.sin(a)*s-1),id=NewProjectile(p.GetProjectileSource_FromThis(),center(p),v,t,Math.max(1,Math.floor(N(p.damage)*.5)),0,p.owner,0,0,0,null);try{const q=Terraria.Main.projectile[id];if(q)MarkRogueProjectile(q,'AshenStalactite',true);}catch(_){}}}}
export class AshenStalactiteDebris extends ModProjectile{constructor(){super();this.Texture='Items/Weapons/Rogue/AshenStalactite';}SetDefaults(){const p=this.Projectile;p.width=12;p.height=12;p.friendly=true;p.penetrate=-1;p.timeLeft=50;p.usesIDStaticNPCImmunity=true;p.idStaticNPCHitCooldown=10;p.aiStyle=-1;p.scale=.55;}OnSpawn(p){MarkRogueProjectile(p,'AshenStalactite',true);}AI(p){p.rotation=N(p.rotation)+.2;p.velocity=Vector2.new(N(p.velocity.X),Math.min(16,N(p.velocity.Y)+.2));}OnTileCollide(){return true;}}

export class CinquedeaProj extends ModProjectile{
 constructor(){super();this.Texture='Items/Weapons/Rogue/Cinquedea';}
 SetDefaults(){const p=this.Projectile;p.width=10;p.height=10;p.friendly=true;p.penetrate=2;p.timeLeft=600;p.tileCollide=false;p.usesIDStaticNPCImmunity=true;p.idStaticNPCHitCooldown=10;p.aiStyle=-1;}
 OnSpawn(p){MarkRogueProjectile(p,'Cinquedea',false);FusionEntityData.GetProjectileBag(p,'cinquedea',()=>({age:0,stick:0,target:-1,off:Vector2.Zero,stored:p.velocity,released:false}));}
 CanDamage(p){const s=FusionEntityData.GetProjectileBag(p,'cinquedea',()=>({age:0,stick:0,target:-1,off:Vector2.Zero,stored:p.velocity,released:false}));return s.stick>0?false:null;}
 AI(p){const s=FusionEntityData.GetProjectileBag(p,'cinquedea',()=>({age:0,stick:0,target:-1,off:Vector2.Zero,stored:p.velocity,released:false}));s.age++;if(s.age>2)p.tileCollide=true;if(s.stick>0){let n=FrozenCubeNPC(s.target);if(!valid(n,p)){s.stick=0;s.released=true;p.velocity=Vector2.Multiply(norm(s.stored),22);p.tileCollide=true;return;}p.Center=Vector2.Add(center(n),s.off);p.velocity=Vector2.Zero;s.stick--;if(s.stick===0){s.released=true;p.velocity=Vector2.Multiply(norm(s.stored),22);p.extraUpdates=2;p.timeLeft=Math.min(N(p.timeLeft,90),90);p.tileCollide=true;}return;}p.spriteDirection=p.direction=N(p.velocity.X)>=0?1:-1;/* A Cinquedea é espelhada pelo renderer: no lado esquerdo precisa de +135° para a ponta continuar na frente. */p.rotation=Math.atan2(N(p.velocity.Y),N(p.velocity.X))+(p.spriteDirection===1?Math.PI/4:Math.PI*3/4);if(!IsStealthStrike(p)&&s.age>80)p.velocity=Vector2.new(N(p.velocity.X),Math.min(10,N(p.velocity.Y)+.15));}
 OnHitNPC(p,npc){const s=FusionEntityData.GetProjectileBag(p,'cinquedea',()=>({age:0,stick:0,target:-1,off:Vector2.Zero,stored:p.velocity,released:false}));if(IsStealthStrike(p)&&!s.released&&s.stick<=0){s.target=Math.floor(N(npc.whoAmI,-1));s.off=Vector2.new(N(center(p).X)-N(center(npc).X),N(center(p).Y)-N(center(npc).Y));s.stored=p.velocity;s.stick=30;p.penetrate=-1;p.tileCollide=false;}}
 OnTileCollide(){return true;}
}

export class GleamingDaggerProj extends ModProjectile{
 constructor(){super();this.Texture='Items/Weapons/Rogue/GleamingDagger';}
 SetDefaults(){const p=this.Projectile;p.width=12;p.height=12;p.friendly=true;p.penetrate=2;p.timeLeft=600;p.usesIDStaticNPCImmunity=true;p.idStaticNPCHitCooldown=10;p.aiStyle=-1;}
 OnSpawn(p){MarkRogueProjectile(p,'GleamingDagger',false);FusionEntityData.GetProjectileBag(p,'gleaming',()=>({hit:false,target:-1,seen:new Set(),age:0}));}
 AI(p){const s=FusionEntityData.GetProjectileBag(p,'gleaming',()=>({hit:false,target:-1,seen:new Set(),age:0}));s.age++;if(s.hit)p.rotation=N(p.rotation)+N(p.direction,1)*.4;else{p.spriteDirection=p.direction=N(p.velocity.X)>=0?1:-1;/* Mesmo ajuste para a textura diagonal: o flip nativo exige sinal oposto no lado esquerdo. */p.rotation=Math.atan2(N(p.velocity.Y),N(p.velocity.X))+(p.spriteDirection===1?Math.PI/4:-Math.PI/4);}if(IsStealthStrike(p)&&s.hit&&s.target>=0){const n=FrozenCubeNPC(s.target);if(valid(n,p))p.velocity=toward(center(p),center(n),15);}else if(!IsStealthStrike(p)&&s.age>25)p.velocity=Vector2.new(N(p.velocity.X),Math.min(16,N(p.velocity.Y)+.5));if(Math.random()<1/9)dust(p,244,1);}
 OnHitNPC(p,npc){const s=FusionEntityData.GetProjectileBag(p,'gleaming',()=>({hit:false,target:-1,seen:new Set(),age:0}));s.seen.add(Math.floor(N(npc.whoAmI,-1)));const n=target(p,999,s.seen);if(n){if(IsStealthStrike(p))p.damage=Math.max(1,Math.floor(N(p.damage)*1.05));s.hit=true;s.target=Math.floor(N(n.whoAmI,-1));p.velocity=toward(center(p),center(n),15);}}
 OnTileCollide(){return true;}OnKill(p){dust(p,244,6);}
}
