import { Terraria, Modules } from './../../../../TL/ModImports.js';
import { ModItem } from './../../../../TL/ModItem.js';
import { ModBuff } from './../../../../TL/ModBuff.js';
import { ModProjectile } from './../../../../TL/ModProjectile.js';
const { Vector2 }=Modules;
const NewProjectile=Terraria.Projectile['int NewProjectile(IEntitySource spawnSource, Vector2 position, Vector2 velocity, int Type, int Damage, float KnockBack, int Owner, float ai0, float ai1, float ai2, NewProjectileModifier modifer)'];
function src(p,i){try{return p['IEntitySource GetProjectileSource_Item(Item item)'](i);}catch(_){return null;}}
function spawned(id){try{return Terraria.Main.projectile.get_Item(Number(id));}catch(_){return null;}}
function safeSpawn(pos,player,w,h){const x=Number(pos?.X)||0,y=Number(pos?.Y)||0;function solid(c){try{return Terraria.Collision['bool SolidCollision(Vector2 Position, int Width, int Height)'](Vector2.new((Number(c.X)||0)-w/2,(Number(c.Y)||0)-h/2),w,h);}catch(_){return false;}}const wanted=Vector2.new(x,y);if(!solid(wanted))return wanted;let base=null;try{base=player.MountedCenter;}catch(_){base=Vector2.new(x,y);}for(const oy of [-40,-72,-104,40]){const c=Vector2.new(Number(base.X)||x,(Number(base.Y)||y)+oy);if(!solid(c))return c;}return base;}
function setNative(holder,name,index,value){try{let a=holder[name],need=Number(index)+1,len=Number(a&&a.Length);if(!Number.isFinite(len))len=Number(a&&a.length)||0;if(len<need){a=a.cloneResized(need);holder[name]=a;}try{a.set_Item(Number(index),value);return true;}catch(_){}try{a['void SetValue(Object value, int index)'](value,Number(index));return true;}catch(_){}return false;}catch(_){return false;}}
export class EyeOfNight extends ModItem{
 constructor(){super();this.Texture='Items/Weapons/Summon/EyeOfNight';this.ResearchUnlockCount=1;}
 SetStaticDefaults(){setNative(Terraria.ID.ItemID.Sets,'GamepadWholeScreenUseRange',this.Type,true);try{Terraria.ID.ItemID.Sets.GamepadWholeScreenUseRange[this.Type]=true;}catch(_){}setNative(Terraria.ID.ItemID.Sets,'LockOnIgnoresCollision',this.Type,true);try{Terraria.ID.ItemID.Sets.LockOnIgnoresCollision[this.Type]=true;}catch(_){}setNative(Terraria.ID.ItemID.Sets,'StaffMinionSlotsRequired',this.Type,1);try{Terraria.ID.ItemID.Sets.StaffMinionSlotsRequired[this.Type]=1;}catch(_){} }
 SetDefaults(){try{this.CloneDefaults(Terraria.ID.ItemID.BabyBirdStaff);}catch(_){}const i=this.Item;i.width=36;i.height=36;i.damage=24;i.summon=true;i.knockBack=1;i.mana=10;i.useAnimation=i.useTime=36;i.useStyle=Terraria.ID.ItemUseStyleID.Swing;i.noMelee=true;i.autoReuse=true;i.UseSound=Terraria.ID.SoundID.NPCHit1;i.rare=Terraria.ID.ItemRarityID.Orange;i.value=Terraria.Item.buyPrice(0,4,0,0);i.buffType=ModBuff.getTypeByName('EyeOfNightBuff');i.shoot=ModProjectile.getTypeByName('EyeOfNightSummon');i.shootSpeed=0;this.MenuCategories.push('summon');}
 ModifyShootStats(item,player,stats){try{stats.position=safeSpawn(Terraria.Main.MouseWorld,player,16,16);stats.velocity=Vector2.new(0,-3);}catch(_){}}
 Shoot(item,player,position,velocity,type,damage,kb){const t=Number(ModProjectile.getTypeByName('EyeOfNightSummon')||0),b=Number(ModBuff.getTypeByName('EyeOfNightBuff')||0);if(!(t>0&&b>0))return false;try{player.AddBuff(b,2,false);}catch(_){}const base=Math.max(1,Math.floor(Number(item.damage)||24)),spawnDamage=Math.max(1,Math.floor(Number(damage)>0?Number(damage):base)),id=NewProjectile(src(player,item),position,Vector2.new(0,-3),t,spawnDamage,Number(kb)||1,Terraria.PlayerIndex(player),0,0,0,null),p=spawned(id);if(p){p.damage=spawnDamage;p.originalDamage=base;p.minionSlots=1;p.friendly=true;p.hostile=false;p.netUpdate=true;}return false;}
 AddRecipes(){const gel=Number(ModItem.getTypeByName('PurifiedGel')||0),bell=Number(ModItem.getTypeByName('BelladonnaSpiritStaff')||0),vile=Number(ModItem.getTypeByName('VileFeeder')||0),scab=Number(ModItem.getTypeByName('ScabRipper')||0),necro=Number(ModItem.getTypeByName('StaffOfNecrosteocytes')||0);if(!(gel>0&&bell>0&&necro>0))return;const imp=Number(Terraria.ID.ItemID.ImpStaff||2365),altar=Number(Terraria.ID.TileID.DemonAltar||26);if(vile>0)this.CreateRecipe().AddIngredient(vile,1).AddIngredient(necro,1).AddIngredient(bell,1).AddIngredient(imp,1).AddIngredient(gel,10).AddTile(altar).Register();if(scab>0)this.CreateRecipe().AddIngredient(scab,1).AddIngredient(necro,1).AddIngredient(bell,1).AddIngredient(imp,1).AddIngredient(gel,10).AddTile(altar).Register();}
}
