import { Terraria, Modules } from './../../../../TL/ModImports.js';
import { ModItem } from './../../../../TL/ModItem.js';
import { ModBuff } from './../../../../TL/ModBuff.js';
import { ModProjectile } from './../../../../TL/ModProjectile.js';
const { Vector2 }=Modules;
const NewProjectile=Terraria.Projectile['int NewProjectile(IEntitySource spawnSource, Vector2 position, Vector2 velocity, int Type, int Damage, float KnockBack, int Owner, float ai0, float ai1, float ai2, NewProjectileModifier modifer)'];
function src(p,i){try{return p['IEntitySource GetProjectileSource_Item(Item item)'](i);}catch(_){try{return null;}catch(__){return null;}}}
function spawned(id){try{return Terraria.Main.projectile.get_Item(Number(id));}catch(_){return null;}}
function safeSpawn(pos,player,w,h){const x=Number(pos?.X)||0,y=Number(pos?.Y)||0;function solid(c){try{return Terraria.Collision['bool SolidCollision(Vector2 Position, int Width, int Height)'](Vector2.new((Number(c.X)||0)-w/2,(Number(c.Y)||0)-h/2),w,h);}catch(_){return false;}}const wanted=Vector2.new(x,y);if(!solid(wanted))return wanted;let base=null;try{base=player.MountedCenter;}catch(_){base=Vector2.new(x,y);}for(const oy of [-40,-72,-104,40]){const c=Vector2.new(Number(base.X)||x,(Number(base.Y)||y)+oy);if(!solid(c))return c;}return base;}
function setNative(holder,name,index,value){try{let a=holder[name],need=Number(index)+1,len=Number(a&&a.Length);if(!Number.isFinite(len))len=Number(a&&a.length)||0;if(len<need){a=a.cloneResized(need);holder[name]=a;}try{a.set_Item(Number(index),value);return true;}catch(_){}try{a['void SetValue(Object value, int index)'](value,Number(index));return true;}catch(_){}return false;}catch(_){return false;}}
export class ScabRipper extends ModItem{
 constructor(){super();this.Texture='Items/Weapons/Summon/ScabRipper';this.ResearchUnlockCount=1;}
 SetStaticDefaults(){setNative(Terraria.Item,'staff',this.Type,true);try{Terraria.Item.staff[this.Type]=true;}catch(_){}setNative(Terraria.ID.ItemID.Sets,'GamepadWholeScreenUseRange',this.Type,true);try{Terraria.ID.ItemID.Sets.GamepadWholeScreenUseRange[this.Type]=true;}catch(_){}setNative(Terraria.ID.ItemID.Sets,'LockOnIgnoresCollision',this.Type,true);try{Terraria.ID.ItemID.Sets.LockOnIgnoresCollision[this.Type]=true;}catch(_){}setNative(Terraria.ID.ItemID.Sets,'StaffMinionSlotsRequired',this.Type,1);try{Terraria.ID.ItemID.Sets.StaffMinionSlotsRequired[this.Type]=1;}catch(_){} }
 SetDefaults(){try{this.CloneDefaults(Terraria.ID.ItemID.BabyBirdStaff);}catch(_){}const i=this.Item;i.width=66;i.height=70;i.damage=15;i.summon=true;i.knockBack=.5;i.mana=10;i.useAnimation=i.useTime=36;i.noMelee=true;i.autoReuse=true;i.useStyle=Terraria.ID.ItemUseStyleID.Shoot;i.UseSound=Terraria.ID.SoundID.Item83;i.rare=Terraria.ID.ItemRarityID.Green;i.value=Terraria.Item.buyPrice(0,0,40,0);i.buffType=ModBuff.getTypeByName('BabyBloodCrawlerBuff');i.shoot=ModProjectile.getTypeByName('BabyBloodCrawler');i.shootSpeed=1;this.MenuCategories.push('summon');}
 ModifyShootStats(item,player,stats){try{stats.position=safeSpawn(Terraria.Main.MouseWorld,player,26,26);stats.velocity=Vector2.Zero;}catch(_){}}
 Shoot(item,player,position,velocity,type,damage,kb){const t=Number(ModProjectile.getTypeByName('BabyBloodCrawler')||0),b=Number(ModBuff.getTypeByName('BabyBloodCrawlerBuff')||0);if(!(t>0&&b>0))return false;try{player.AddBuff(b,2,false);}catch(_){}const base=Math.max(1,Math.floor(Number(item.damage)||15)),spawnDamage=Math.max(1,Math.floor(Number(damage)>0?Number(damage):base)),id=NewProjectile(src(player,item),position,Vector2.Zero,t,spawnDamage,Number(kb)||.5,Terraria.PlayerIndex(player),0,0,0,null),p=spawned(id);if(p){p.damage=spawnDamage;p.originalDamage=base;p.minionSlots=1;p.friendly=true;p.hostile=false;p.netUpdate=true;}return false;}
 AddRecipes(){this.CreateRecipe().AddIngredient(Terraria.ID.ItemID.CrimtaneBar,5).AddIngredient(Terraria.ID.ItemID.TissueSample,9).AddIngredient(Terraria.ID.ItemID.Shadewood,20).AddTile(Terraria.ID.TileID.Anvils).Register();}
}
