import { PreSlimeGodAccessoryPlayer } from './../Content/Global/PreSlimeGodAccessoryPlayer.js';
import { DraedonTier1InputPlayer } from './../Content/Global/DraedonTier1InputPlayer.js';
import { FusionCameraPlayer } from './../Content/Global/FusionCameraPlayer.js';
import { AcrobaticFishingPlayer } from './../Content/Global/AcrobaticFishingPlayer.js';
import { AerialiteAccessoryPlayer } from './../Content/Global/AerialiteAccessoryPlayer.js';
import { SulphurousArmorPlayer } from './../Content/Global/SulphurousArmorPlayer.js';
import { OnyxLabGlobalTile } from './../Content/Tiles/OnyxLabGlobalTile.js';
import { UnderworldLabGlobalTile } from './../Content/Tiles/UnderworldLabGlobalTile.js';
import { SunkenSeaLabGlobalTile } from './../Content/Tiles/SunkenSeaLabGlobalTile.js';
import { IceLabGlobalTile } from './../Content/Tiles/IceLabGlobalTile.js';
import { JungleLabGlobalTile } from './../Content/Tiles/JungleLabGlobalTile.js';
import { PlanetoidLabGlobalTile } from './../Content/Tiles/PlanetoidLabGlobalTile.js';
import { VernalSoilGlobalTile } from './../Content/Tiles/VernalSoilGlobalTile.js';
import { ModPlayer } from './../TL/ModPlayer.js';
import { GlobalNPC } from './../TL/GlobalNPC.js';
import { GlobalTile } from './../TL/GlobalTile.js';
import { GlobalProjectile } from './../TL/GlobalProjectile.js';
import { GlobalItem } from './../TL/GlobalItem.js';
import { PortDiagnostics } from './../Content/Global/PortDiagnostics.js';
import { CalamityPlayerState } from './../Core/CalamityPlayerState.js';
import { WulfrumControllerPlayer } from './../Content/Global/WulfrumControllerPlayer.js';
import { BrokenBiomeBladeInputPlayer } from './../Content/Global/BrokenBiomeBladeInputPlayer.js';
import { RoverDrivePlayer } from './../Content/Global/RoverDrivePlayer.js';
import { LuxorPlayer } from './../Content/Global/LuxorPlayer.js';
import { CalamityGlobalNPC } from './../Content/Global/CalamityGlobalNPC.js';
import { FilthyGloveGlobalProjectile } from './../Content/Global/FilthyGloveGlobalProjectile.js';
import { DesertScourgeTrophyGlobalTile } from './../Content/Tiles/DesertScourgeTrophyGlobalTile.js';
import { DesertScourgeRelicGlobalTile } from './../Content/Tiles/DesertScourgeRelicGlobalTile.js';
import { CrabulonTrophyGlobalTile } from './../Content/Tiles/CrabulonTrophyGlobalTile.js';
import { CrabulonRelicGlobalTile } from './../Content/Tiles/CrabulonRelicGlobalTile.js';
import { HiveMindTrophyGlobalTile } from './../Content/Tiles/HiveMindTrophyGlobalTile.js';
import { HiveMindRelicGlobalTile } from './../Content/Tiles/HiveMindRelicGlobalTile.js';
import { ThankYouPaintingGlobalTile } from './../Content/Tiles/ThankYouPaintingGlobalTile.js';
import { BloodstainedGloveGlobalProjectile } from './../Content/Global/BloodstainedGloveGlobalProjectile.js';
import { PerforatorTrophyGlobalTile } from './../Content/Tiles/PerforatorTrophyGlobalTile.js';
import { PerforatorRelicGlobalTile } from './../Content/Tiles/PerforatorRelicGlobalTile.js';
import { SlimeGodTrophyGlobalTile } from './../Content/Tiles/SlimeGodTrophyGlobalTile.js';
import { GiantClamTrophyGlobalTile } from './../Content/Tiles/GiantClamTrophyGlobalTile.js';
import { GiantClamRelicGlobalTile } from './../Content/Tiles/GiantClamRelicGlobalTile.js';
import { SlimeGodRelicGlobalTile } from './../Content/Tiles/SlimeGodRelicGlobalTile.js';
import { WulfrumBobberVisualGlobalProjectile } from './../Content/Global/WulfrumBobberVisualGlobalProjectile.js';
import { VictideGlobalItem } from './../Content/Global/VictideGlobalItem.js';
import { RogueGlobalItem } from './../Content/Global/RogueGlobalItem.js';
import { SunkenSeaMaterialGlobalTile } from './../Content/Tiles/SunkenSeaMaterialGlobalTile.js';
import { SulphurousSeaMaterialGlobalTile } from './../Content/Tiles/SulphurousSeaMaterialGlobalTile.js';
import { IronBallPlacedGlobalTile } from './../Content/Tiles/IronBallPlacedGlobalTile.js';

import { AerialiteGlobalTile } from './../Content/Tiles/AerialiteGlobalTile.js';
import { GraniteShrineAccessoryPlayer } from './../Content/Global/GraniteShrineAccessoryPlayer.js';
import { SurfaceShrineAccessoryPlayer } from './../Content/Global/SurfaceShrineAccessoryPlayer.js';
import { FrozenCubePlayer } from './../Content/Global/FrozenCubePlayer.js';
import { FungalSymbiotePlayer } from './../Content/Global/FungalSymbiotePlayer.js';
import { FungalSymbioteGlobalItem } from './../Content/Global/FungalSymbioteGlobalItem.js';
import { EffigyPlayer } from './../Content/Global/EffigyPlayer.js';
import { EffigyGlobalTile } from './../Content/Tiles/EffigyGlobalTile.js';
import { InkBombPlayer } from './../Content/Global/InkBombPlayer.js';
import { StatigelPlayer } from './../Content/Global/StatigelPlayer.js';
import { DesertProwlerPlayer } from './../Content/Global/DesertProwlerPlayer.js';
import { MarniteArchitectPlayer } from './../Content/Global/MarniteArchitectPlayer.js';
import { PreHardmodeBatch11Player } from './../Content/Global/PreHardmodeBatch11Player.js';
import { CnidarianTagGlobalProjectile } from './../Content/Global/CnidarianTagGlobalProjectile.js';
export function RegisterGlobal() {
    ModPlayer.register(CalamityPlayerState);
    ModPlayer.register(WulfrumControllerPlayer);
    ModPlayer.register(BrokenBiomeBladeInputPlayer);
    ModPlayer.register(RoverDrivePlayer);
    ModPlayer.register(LuxorPlayer);
    ModPlayer.register(PortDiagnostics);
    ModPlayer.register(GraniteShrineAccessoryPlayer);
    ModPlayer.register(SurfaceShrineAccessoryPlayer);
    ModPlayer.register(FrozenCubePlayer);
    ModPlayer.register(FungalSymbiotePlayer);
    ModPlayer.register(EffigyPlayer);
    GlobalNPC.register(CalamityGlobalNPC);
    GlobalItem.register(VictideGlobalItem);
    GlobalItem.register(RogueGlobalItem);
    GlobalItem.register(FungalSymbioteGlobalItem);
    GlobalProjectile.register(FilthyGloveGlobalProjectile);
    GlobalProjectile.register(BloodstainedGloveGlobalProjectile);
    GlobalProjectile.register(WulfrumBobberVisualGlobalProjectile);
    GlobalProjectile.register(CnidarianTagGlobalProjectile);
    GlobalTile.register(DesertScourgeTrophyGlobalTile);
    GlobalTile.register(DesertScourgeRelicGlobalTile);
    GlobalTile.register(CrabulonTrophyGlobalTile);
    GlobalTile.register(CrabulonRelicGlobalTile);
    GlobalTile.register(HiveMindTrophyGlobalTile);
    GlobalTile.register(HiveMindRelicGlobalTile);
    GlobalTile.register(ThankYouPaintingGlobalTile);
    GlobalTile.register(PerforatorTrophyGlobalTile);
    GlobalTile.register(PerforatorRelicGlobalTile);
    GlobalTile.register(SlimeGodTrophyGlobalTile);
    GlobalTile.register(SlimeGodRelicGlobalTile);
    GlobalTile.register(GiantClamTrophyGlobalTile);
    GlobalTile.register(GiantClamRelicGlobalTile);
    GlobalTile.register(SunkenSeaMaterialGlobalTile);
    GlobalTile.register(SulphurousSeaMaterialGlobalTile);
    GlobalTile.register(IronBallPlacedGlobalTile);
    GlobalTile.register(AerialiteGlobalTile);
    GlobalTile.register(PlanetoidLabGlobalTile);
    GlobalTile.register(JungleLabGlobalTile);
    GlobalTile.register(IceLabGlobalTile);
    GlobalTile.register(VernalSoilGlobalTile);
    GlobalTile.register(EffigyGlobalTile);
    ModPlayer.register(InkBombPlayer);
    ModPlayer.register(StatigelPlayer);
    ModPlayer.register(DesertProwlerPlayer);
    ModPlayer.register(SulphurousArmorPlayer);
    ModPlayer.register(AerialiteAccessoryPlayer);
    GlobalTile.register(SunkenSeaLabGlobalTile);
    GlobalTile.register(UnderworldLabGlobalTile);
    GlobalTile.register(OnyxLabGlobalTile);
    // Phase 13.13.0: append-only player runtime registration.
    ModPlayer.register(AcrobaticFishingPlayer);
    // Phase 13.14.0: mobile secondary-use bridge for Tier 1 Arsenal weapons.
    ModPlayer.register(DraedonTier1InputPlayer);
    // Phase 13.14.0.11: câmera cinematográfica leve, sem hook novo.
    ModPlayer.register(FusionCameraPlayer);
    // Phase 13.26.1: two-piece Marnite Architect set + lift runtime.
    ModPlayer.register(MarniteArchitectPlayer);
    // Phase 13.26.4: Sunken Sea Driftwood fishing acquisition.
    ModPlayer.register(PreHardmodeBatch11Player);
    // Phase 13.26.5: pre-Slime God accessory runtime.
    ModPlayer.register(PreSlimeGodAccessoryPlayer);

}
