import { DraedonTier1System } from './../Content/Systems/DraedonTier1System.js';
import { BossChecklistCompatibilitySystem } from './../Content/Systems/BossChecklistCompatibilitySystem.js';
import { GiantHiveVisualSystem } from './../Content/Systems/GiantHiveVisualSystem.js';
import { GiantHiveChestRepairSystem } from './../Content/Systems/GiantHiveChestRepairSystem.js';
import { VernalPassChestRepairSystem } from './../Content/Systems/VernalPassChestRepairSystem.js';
import { VernalSoilSystem } from './../Content/Systems/VernalSoilSystem.js';
import { VernalPassTerrainVisualSystem } from './../Content/Systems/VernalPassTerrainVisualSystem.js';
import { StatigelJumpHookSystem } from './../Content/Systems/StatigelJumpHookSystem.js';
import { BrokenBiomeBladeSystem } from './../Content/Systems/BrokenBiomeBladeSystem.js';
import { OverloadedSludgeRecipeSystem } from './../Content/Systems/OverloadedSludgeRecipeSystem.js';
import { StatigelRecipeSystem } from './../Content/Systems/StatigelRecipeSystem.js';
import { PostSlimeGodRecipeSystem } from './../Content/Systems/PostSlimeGodRecipeSystem.js';
import { RoxShrineVisualSystem } from './../Content/Systems/RoxShrineVisualSystem.js';
import { ModSystem } from './../TL/ModSystem.js';
import { ModLoader } from './../TL/Core/ModLoader.js';
import { GlobalHooks } from './../TL/GlobalHooks.js';
import { CalamityWorldState } from './../Core/CalamityWorldState.js';
import { FusionCoreSystem } from './../Core/FusionCoreSystem.js';
import { AndroidBossSoundSystem } from './../Content/Systems/AndroidBossSoundSystem.js';
import { DesertScourgeTrophySystem } from './../Content/Systems/DesertScourgeTrophySystem.js';
import { DesertScourgeRelicSystem } from './../Content/Systems/DesertScourgeRelicSystem.js';
import { CrabulonTrophySystem } from './../Content/Systems/CrabulonTrophySystem.js';
import { CrabulonRelicSystem } from './../Content/Systems/CrabulonRelicSystem.js';
import { HiveMindTrophySystem } from './../Content/Systems/HiveMindTrophySystem.js';
import { HiveMindRelicSystem } from './../Content/Systems/HiveMindRelicSystem.js';
import { ThankYouPaintingSystem } from './../Content/Systems/ThankYouPaintingSystem.js';
import { PerforatorTrophySystem } from './../Content/Systems/PerforatorTrophySystem.js';
import { PerforatorRelicSystem } from './../Content/Systems/PerforatorRelicSystem.js';
import { SlimeGodTrophySystem } from './../Content/Systems/SlimeGodTrophySystem.js';
import { GiantClamTrophySystem } from './../Content/Systems/GiantClamTrophySystem.js';
import { GiantClamRelicSystem } from './../Content/Systems/GiantClamRelicSystem.js';
import { SlimeGodRelicSystem } from './../Content/Systems/SlimeGodRelicSystem.js';
import { SunkenSeaPreviewSystem } from './../Content/Systems/SunkenSeaPreviewSystem.js';
import { SunkenSeaMaterialSystem } from './../Content/Systems/SunkenSeaMaterialSystem.js';
import { SunkenSeaTerrainSystem } from './../Content/Systems/SunkenSeaTerrainSystem.js';
import { SunkenSeaTerrainVisualSystem } from './../Content/Systems/SunkenSeaTerrainVisualSystem.js';
import { SunkenSeaEcologySystem } from './../Content/Systems/SunkenSeaEcologySystem.js';
import { SulphurousSeaPreviewSystem } from './../Content/Systems/SulphurousSeaPreviewSystem.js';
import { SulphurousSeaMaterialSystem } from './../Content/Systems/SulphurousSeaMaterialSystem.js';
import { SulphurousSeaTerrainSystem } from './../Content/Systems/SulphurousSeaTerrainSystem.js';
import { SulphurousSeaDetailRecoverySystem } from './../Content/Systems/SulphurousSeaDetailRecoverySystem.js';
import { SulphurousSeaAmbienceRecoverySystem } from './../Content/Systems/SulphurousSeaAmbienceRecoverySystem.js';
import { SulphurousSeaProxyRepairSystem } from './../Content/Systems/SulphurousSeaProxyRepairSystem.js';
import { SulphurousSeaRustyChestRepairSystem } from './../Content/Systems/SulphurousSeaRustyChestRepairSystem.js';
import { IronBallWorldgenSystem } from './../Content/Systems/IronBallWorldgenSystem.js';
import { OceanSpiritLightPetSystem } from './../Content/Systems/OceanSpiritLightPetSystem.js';
import { TrashmanPetSystem } from './../Content/Systems/TrashmanPetSystem.js';
import { SafeItemRegistryCompatibilitySystem } from './../Content/Systems/SafeItemRegistryCompatibilitySystem.js';
import { AbyssTerrainSystem } from './../Content/Systems/AbyssTerrainSystem.js';
import { AbyssTreasureChestSystem } from './../Content/Systems/AbyssTreasureChestSystem.js';
import { AbyssAmbientLightSystem } from './../Content/Systems/AbyssAmbientLightSystem.js';
import { AbyssAmbientProxyRepairSystem } from './../Content/Systems/AbyssAmbientProxyRepairSystem.js';
import { AbyssMusicSystem } from './../Content/Systems/AbyssMusicSystem.js';
import { AbyssVanillaSpawnSuppressionSystem } from './../Content/Systems/AbyssVanillaSpawnSuppressionSystem.js';
import { SulphurousSeaTerrainVisualSystem } from './../Content/Systems/SulphurousSeaTerrainVisualSystem.js';
import { AcidRainTier1System } from './../Content/Systems/AcidRainTier1System.js';
import { BiomeAnchorCompatibilitySystem } from './../Content/Systems/BiomeAnchorCompatibilitySystem.js';
import { BiomeAnchorMigrationSystem } from './../Content/Systems/BiomeAnchorMigrationSystem.js';
import { NativeRelicDropCleanup } from './../Core/NativeRelicDropCleanup.js';
import { RegisterDusts } from './RegisterDusts.js';
import { RegisterBuffs } from './RegisterBuffs.js';
import { RegisterItems } from './RegisterItems.js';
import { RegisterProjectiles } from './RegisterProjectiles.js';
import { RegisterNPCs } from './RegisterNPCs.js';
import { RegisterGlobal } from './RegisterGlobal.js';
import { RegisterBackgrounds } from './RegisterBackgrounds.js';
import { RegisterBiomes } from './RegisterBiomes.js';
import { RegisterMenus } from './RegisterMenus.js';
import { RegisterMounts } from './RegisterMounts.js';
import { RipperUIHooks } from './../Content/UI/RipperUIHooks.js';
import { AcidRainUIHooks } from './../Content/UI/AcidRainUIHooks.js';
import { BrittleStarModeUIHooks } from './../Content/UI/BrittleStarModeUIHooks.js';
import { SaharaSlicersUIHooks } from './../Content/UI/SaharaSlicersUIHooks.js';
import { WulfrumBastionUIHooks } from './../Content/UI/WulfrumBastionUIHooks.js';
import { WulfrumDroidModeUIHooks } from './../Content/UI/WulfrumDroidModeUIHooks.js';
import { RoverDriveUIHooks } from './../Content/UI/RoverDriveUIHooks.js';
import { RogueStealthUIHooks } from './../Content/UI/RogueStealthUIHooks.js';
import { DesertScourgeTrophyDrawHooks } from './../Content/UI/DesertScourgeTrophyDrawHooks.js';
import { FusionRenderHooks } from './../Content/UI/FusionRenderHooks.js';
import { PostSlimeGodProjectileVisualHooks } from './../Content/UI/PostSlimeGodProjectileVisualHooks.js';
import { SunkenSeaEcologyDrawHooks } from './../Content/UI/SunkenSeaEcologyDrawHooks.js';
import { WorldInteraction } from './../Content/Global/WorldInteraction.js';

import { AerialiteProgressionSystem } from './../Content/Systems/AerialiteProgressionSystem.js';
import { AerialiteMaterialSystem } from './../Content/Systems/AerialiteMaterialSystem.js';
import { AerialiteCompatibilitySystem } from './../Content/Systems/AerialiteCompatibilitySystem.js';
import { AerialiteTerrainVisualSystem } from './../Content/Systems/AerialiteTerrainVisualSystem.js';
import { DesertShrineChestRepairSystem } from './../Content/Systems/DesertShrineChestRepairSystem.js';
import { GraniteShrineChestRepairSystem } from './../Content/Systems/GraniteShrineChestRepairSystem.js';
import { SurfaceShrineChestRepairSystem } from './../Content/Systems/SurfaceShrineChestRepairSystem.js';
import { MarbleShrineChestRepairSystem } from './../Content/Systems/MarbleShrineChestRepairSystem.js';
import { IceShrineChestRepairSystem } from './../Content/Systems/IceShrineChestRepairSystem.js';
import { MushroomShrineChestRepairSystem } from './../Content/Systems/MushroomShrineChestRepairSystem.js';
import { EvilShrineChestRepairSystem } from './../Content/Systems/EvilShrineChestRepairSystem.js';
import { EffigySystem } from './../Content/Systems/EffigySystem.js';
import { EffigyDrawHooks } from './../Content/UI/EffigyDrawHooks.js';
import { LabStructureOverlayHooks } from './../Content/UI/LabStructureOverlayHooks.js';
import { ShimmerShrineChestRepairSystem } from './../Content/Systems/ShimmerShrineChestRepairSystem.js';
import { AbyssShrineVisualSystem } from './../Content/Systems/AbyssShrineVisualSystem.js';
import { AbyssShrineChestRepairSystem } from './../Content/Systems/AbyssShrineChestRepairSystem.js';
import { WorldEvilIslandChestRepairSystem } from './../Content/Systems/WorldEvilIslandChestRepairSystem.js';
import { PlanetoidLabChestRepairSystem } from './../Content/Systems/PlanetoidLabChestRepairSystem.js';
import { PlanetoidLabVisualSystem } from './../Content/Systems/PlanetoidLabVisualSystem.js';
import { JungleLabChestRepairSystem } from './../Content/Systems/JungleLabChestRepairSystem.js';
import { JungleLabVisualSystem } from './../Content/Systems/JungleLabVisualSystem.js';
import { IceLabChestRepairSystem } from './../Content/Systems/IceLabChestRepairSystem.js';
import { SunkenSeaLabChestRepairSystem } from './../Content/Systems/SunkenSeaLabChestRepairSystem.js';
import { LabInvisibleAnchorSystem } from './../Content/Systems/LabInvisibleAnchorSystem.js';
import { UnderworldLabChestRepairSystem } from './../Content/Systems/UnderworldLabChestRepairSystem.js';
import { OnyxLabChestRepairSystem } from './../Content/Systems/OnyxLabChestRepairSystem.js';
import { OnyxExcavatorRecoverySystem } from './../Content/Systems/OnyxExcavatorRecoverySystem.js';
export function RegisterAll() {
    ModSystem.register(OverloadedSludgeRecipeSystem);
    ModSystem.register(StatigelRecipeSystem);
    ModSystem.register(PostSlimeGodRecipeSystem);
    ModSystem.register(ModLoader);
    ModSystem.register(StatigelJumpHookSystem);
    ModSystem.register(BrokenBiomeBladeSystem);
    ModSystem.register(CalamityWorldState);
    ModSystem.register(FusionCoreSystem);
    ModSystem.register(AndroidBossSoundSystem);
    ModSystem.register(DesertScourgeTrophySystem);
    ModSystem.register(DesertScourgeRelicSystem);
    ModSystem.register(CrabulonTrophySystem);
    ModSystem.register(CrabulonRelicSystem);
    ModSystem.register(HiveMindTrophySystem);
    ModSystem.register(HiveMindRelicSystem);
    ModSystem.register(ThankYouPaintingSystem);
    ModSystem.register(PerforatorTrophySystem);
    ModSystem.register(PerforatorRelicSystem);
    ModSystem.register(SlimeGodTrophySystem);
    ModSystem.register(SlimeGodRelicSystem);
    ModSystem.register(GiantClamTrophySystem);
    ModSystem.register(GiantClamRelicSystem);
    ModSystem.register(SunkenSeaPreviewSystem);
    ModSystem.register(SunkenSeaMaterialSystem);
    ModSystem.register(SunkenSeaTerrainSystem);
    ModSystem.register(SunkenSeaTerrainVisualSystem);
    ModSystem.register(SunkenSeaEcologySystem);
    ModSystem.register(SulphurousSeaPreviewSystem);
    ModSystem.register(SulphurousSeaMaterialSystem);
    ModSystem.register(SulphurousSeaTerrainSystem);
    ModSystem.register(SulphurousSeaDetailRecoverySystem);
    ModSystem.register(SulphurousSeaAmbienceRecoverySystem);
    ModSystem.register(SulphurousSeaProxyRepairSystem);
    ModSystem.register(SulphurousSeaRustyChestRepairSystem);
    ModSystem.register(IronBallWorldgenSystem);
    ModSystem.register(OceanSpiritLightPetSystem);
    ModSystem.register(TrashmanPetSystem);
    ModSystem.register(SafeItemRegistryCompatibilitySystem);
    ModSystem.register(AbyssTerrainSystem);
    ModSystem.register(AbyssTreasureChestSystem);
    ModSystem.register(AbyssAmbientLightSystem);
    ModSystem.register(AbyssAmbientProxyRepairSystem);
    ModSystem.register(AbyssMusicSystem);
    ModSystem.register(AbyssVanillaSpawnSuppressionSystem);
    ModSystem.register(SulphurousSeaTerrainVisualSystem);
    ModSystem.register(AcidRainTier1System);
    ModSystem.register(BiomeAnchorCompatibilitySystem);
    ModSystem.register(BiomeAnchorMigrationSystem);
    ModSystem.register(VernalSoilSystem);
    ModSystem.register(VernalPassTerrainVisualSystem);
    ModSystem.register(VernalPassChestRepairSystem);
    ModSystem.register(GiantHiveVisualSystem);
    ModSystem.register(GiantHiveChestRepairSystem);
    ModSystem.register(NativeRelicDropCleanup);
    GlobalHooks.register(RipperUIHooks);
    // Phase 13.16.0: no new native hook; drawn through the existing shared interface owner.
    GlobalHooks.register(AcidRainUIHooks);
    GlobalHooks.register(BrittleStarModeUIHooks);
    GlobalHooks.register(SaharaSlicersUIHooks);
    GlobalHooks.register(WulfrumBastionUIHooks);
    GlobalHooks.register(WulfrumDroidModeUIHooks);
    GlobalHooks.register(RoverDriveUIHooks);
    GlobalHooks.register(RogueStealthUIHooks);
    GlobalHooks.register(DesertScourgeTrophyDrawHooks);
    GlobalHooks.register(FusionRenderHooks);
    GlobalHooks.register(PostSlimeGodProjectileVisualHooks);
    GlobalHooks.register(SunkenSeaEcologyDrawHooks);
    GlobalHooks.register(WorldInteraction);
    GlobalHooks.register(EffigyDrawHooks);
    GlobalHooks.register(LabStructureOverlayHooks);
    RegisterDusts();
    RegisterBuffs();
    RegisterMounts();
    RegisterProjectiles();
    RegisterItems();
    RegisterNPCs();
    RegisterBackgrounds();
    RegisterBiomes();
    RegisterMenus();
    RegisterGlobal();
    ModSystem.register(AerialiteMaterialSystem);
    ModSystem.register(AerialiteProgressionSystem);
    ModSystem.register(AerialiteCompatibilitySystem);
    ModSystem.register(AerialiteTerrainVisualSystem);
    ModSystem.register(DesertShrineChestRepairSystem);
    ModSystem.register(GraniteShrineChestRepairSystem);
    ModSystem.register(SurfaceShrineChestRepairSystem);
    ModSystem.register(MarbleShrineChestRepairSystem);
    ModSystem.register(IceShrineChestRepairSystem);
    ModSystem.register(MushroomShrineChestRepairSystem);
    ModSystem.register(EvilShrineChestRepairSystem);
    ModSystem.register(EffigySystem);
    ModSystem.register(RoxShrineVisualSystem);
    ModSystem.register(ShimmerShrineChestRepairSystem);
    ModSystem.register(AbyssShrineVisualSystem);
    ModSystem.register(AbyssShrineChestRepairSystem);
    ModSystem.register(WorldEvilIslandChestRepairSystem);
    ModSystem.register(PlanetoidLabChestRepairSystem);
    ModSystem.register(JungleLabChestRepairSystem);
    ModSystem.register(IceLabChestRepairSystem);
    ModSystem.register(LabInvisibleAnchorSystem);
    ModSystem.register(SunkenSeaLabChestRepairSystem);
    ModSystem.register(UnderworldLabChestRepairSystem);
    ModSystem.register(OnyxLabChestRepairSystem);
    ModSystem.register(OnyxExcavatorRecoverySystem);
    ModSystem.register(DraedonTier1System);
    ModSystem.register(BossChecklistCompatibilitySystem);
    try { tl.log('[CalamityPort WorldgenPolicy] live-world structure generation/recovery systems disabled; fresh-world worldgen is authoritative.'); } catch (_) { }
}
