import { Terraria } from './../../TL/ModImports.js';
import { ModSystem } from './../../TL/ModSystem.js';
import { WorldDB } from './../../TL/WorldDB.js';
import { TileData } from './../../TL/Modules/TileData.js';
import { AbyssShrineRuntime, RepairAbyssShrineChestPlacement } from './../../Core/AbyssShrineRuntime.js';
const KEY='calamity:structure:abyssShrine:';
function N(v,f=0){const n=Math.floor(Number(v));return Number.isFinite(n)?n:f;}
function Log(s){try{tl.log(`[CalamityPort AbyssShrineDeferred] ${s}`);}catch(e){}}
function PortWorld(){for(const p of ['mechanicShed','desertShrine','graniteShrine','surfaceShrine','iceShrine','mushroomShrine','marbleShrine','roxShrine','shimmerShrine'])if(WorldDB.get(`calamity:structure:${p}:generated`)===true)return true;return WorldDB.get('calamity:sunkensea:terrain:generated')===true;}
function Save(r){WorldDB.set(KEY+'generated',true);WorldDB.set(KEY+'pending',false);WorldDB.set(KEY+'searchStopped',false);WorldDB.set(KEY+'side',String(r.side));WorldDB.set(KEY+'left',N(r.left));WorldDB.set(KEY+'top',N(r.top));WorldDB.set(KEY+'right',N(r.right));WorldDB.set(KEY+'bottom',N(r.bottom));WorldDB.set(KEY+'chestAnchorX',N(r.chestAnchorX,r.chestX+1));WorldDB.set(KEY+'chestAnchorY',N(r.chestAnchorY,r.chestY-1));WorldDB.set(KEY+'chestX',N(r.chestX));WorldDB.set(KEY+'chestY',N(r.chestY));WorldDB.set(KEY+'chestIndex',N(r.chestIndex,-1));WorldDB.set(KEY+'chestPlacementVersion',2);WorldDB.set(KEY+'roofRows',N(r.roofRows));WorldDB.set(KEY+'smoothCells',JSON.stringify(r.cells||[]));WorldDB.set(KEY+'cellOriginX',N(r.cellOriginX));WorldDB.set(KEY+'cellOriginY',N(r.cellOriginY));WorldDB.set(KEY+'lootVersion',1);WorldDB.set(KEY+'source','official-code-delayed');try{WorldDB.Instance.Save();}catch(e){Log(`metadata save deferred: ${e}`);}const v=ModSystem.getByName('AbyssShrineVisualSystem');if(v&&v.Reload)v.Reload();}
function FilterStoredSmoothCells(chestX,chestY){const ox=N(WorldDB.get(KEY+'cellOriginX'),0),oy=N(WorldDB.get(KEY+'cellOriginY'),0),raw=WorldDB.get(KEY+'smoothCells');if(typeof raw!=='string')return;try{const a=JSON.parse(raw);if(!Array.isArray(a))return;const out=[];for(const e of a){if(!Array.isArray(e)||e.length<4)continue;const wx=ox+N(e[0]),wy=oy+N(e[1]);if(wx>=chestX&&wx<chestX+2&&wy>=chestY&&wy<chestY+2)continue;try{const t=new TileData(wx,wy);if(N(t.type)!==1)continue;}catch(err){continue;}out.push([N(e[0]),N(e[1]),N(e[2]),N(e[3])]);}WorldDB.set(KEY+'smoothCells',JSON.stringify(out));}catch(e){}}
function RepairExistingChest(){if(N(WorldDB.get(KEY+'chestPlacementVersion'),0)>=2)return true;const oldX=N(WorldDB.get(KEY+'chestX'),-1),oldY=N(WorldDB.get(KEY+'chestY'),-1),index=N(WorldDB.get(KEY+'chestIndex'),-1),bottom=N(WorldDB.get(KEY+'bottom'),oldY+3),anchorX=N(WorldDB.get(KEY+'chestAnchorX'),oldX),anchorY=N(WorldDB.get(KEY+'chestAnchorY'),oldY);if(oldX<0||oldY<0)return false;const r=RepairAbyssShrineChestPlacement(anchorX,anchorY,oldX,oldY,index,bottom);if(!r.success){Log(`supported chest repair failed; old=${oldX},${oldY}, target=${r.chestX},${r.chestY}, method=${r.method}.`);return false;}WorldDB.set(KEY+'chestAnchorX',anchorX);WorldDB.set(KEY+'chestAnchorY',anchorY);WorldDB.set(KEY+'chestX',N(r.chestX));WorldDB.set(KEY+'chestY',N(r.chestY));WorldDB.set(KEY+'chestIndex',N(r.chestIndex,-1));WorldDB.set(KEY+'chestPlacementVersion',2);FilterStoredSmoothCells(N(r.chestX),N(r.chestY));try{WorldDB.Instance.Save();}catch(e){}const v=ModSystem.getByName('AbyssShrineVisualSystem');if(v&&v.Reload)v.Reload();Log(`supported chest repair complete; old=${oldX},${oldY}, new=${r.chestX},${r.chestY}, supportY=${bottom}, index=${r.chestIndex}, method=${r.method}.`);return true;}
export class AbyssShrineGenerationSystem extends ModSystem{
 constructor(){super();this.Reset();}Reset(){this.Delay=10800;this.RepairDelay=180;this.Done=false;this.Recovery=false;}OnWorldLoad(){this.Reset();}OnWorldUnload(){this.Reset();}
 Recover(){if(this.Recovery)return;this.Recovery=true;if(WorldDB.get(KEY+'generated')===true||WorldDB.get(KEY+'pending')===true)return;}
 Update(){try{if(Terraria.WorldGen.isGeneratingOrLoadingWorld===true)return;}catch(e){}if(this.Done||!WorldDB.Instance)return;this.Recover();if(WorldDB.get(KEY+'generated')===true){if(N(WorldDB.get(KEY+'chestPlacementVersion'),0)<2){if(this.RepairDelay-->0)return;RepairExistingChest();}this.Done=true;return;}if(this.Delay-->0)return;if(WorldDB.get(KEY+'pending')!==true){this.Done=true;return;}if(N(WorldDB.get(KEY+'deferredVersion'),0)!==2){WorldDB.set(KEY+'pending',false);WorldDB.set(KEY+'stalePendingSuppressed',true);try{WorldDB.Instance.Save();}catch(e){}this.Done=true;Log('suppressed stale legacy pending marker; no background recovery placement started.');return;}if(WorldDB.get('calamity:structure:shimmerShrine:generated')!==true&&WorldDB.get('calamity:structure:shimmerShrine:searchStopped')!==true){this.Delay=300;return;}try{const r=AbyssShrineRuntime.Place();if(r.generated===true){Save(r);this.Done=true;Log(`delayed placement complete; side=${r.side}, chest=${r.chestX},${r.chestY}, smoothCells=${(r.cells||[]).length}, filled=${r.filled}.`);}else{WorldDB.set(KEY+'searchStopped',true);this.Done=true;Log(`placement stopped; reason=${r.reason}. Pending marker preserved.`);}}catch(e){WorldDB.set(KEY+'searchStopped',true);this.Done=true;Log(`placement threw: ${e}`);}}
}
