import { Terraria } from './../../TL/ModImports.js';
import { ModSystem } from './../../TL/ModSystem.js';
import { WorldDB } from './../../TL/WorldDB.js';
import { PostLoadWorkCoordinator } from './../../Core/PostLoadWorkCoordinator.js';
import { IceLabRuntime } from './../../Core/IceLabRuntime.js';
import { IceLabSchematic } from './../../Data/OfficialSchematics/IceLabSchematic.js';
const KEY='calamity:structure:iceLab:',BUDGET=16,PROBE_X=10,PROBE_Y=8;
function I(v,f=0){const n=Math.floor(Number(v));return Number.isFinite(n)?n:f;}
function Active(t){try{return !!t&&t['bool active()']()===true;}catch(e){return false;}}
function TileAt(x,y){try{return Terraria.Main.tile.get_Item(I(x),I(y));}catch(e){return null;}}
function Log(s){try{tl.log(`[CalamityPort IceLabDeferred] ${s}`);}catch(e){}}
function Rect(prefix,defW=0,defH=0){if(!WorldDB.Instance||WorldDB.get(prefix+'generated')!==true)return null;const l=I(WorldDB.get(prefix+'left'),-1),t=I(WorldDB.get(prefix+'top'),-1),w=I(WorldDB.get(prefix+'width'),defW),h=I(WorldDB.get(prefix+'height'),defH);return l>=0&&t>=0&&w>0&&h>0?{l,t,r:l+w,b:t+h}:null;}
function Overlap(a,b,p=55){return !!a&&!!b&&a.l<b.r+p&&a.r>b.l-p&&a.t<b.b+p&&a.b>b.t-p;}
function Hash(x){x=(x^61)^(x>>>16);x=(x+(x<<3))|0;x^=x>>>4;x=Math.imul(x,0x27d4eb2d);x^=x>>>15;return x>>>0;}
function CandidateList(){const W=I(Terraria.Main.maxTilesX,4200),H=I(Terraria.Main.maxTilesY,1200),surf=I(Terraria.Main.worldSurface,250),under=I(Terraria.Main.UnderworldLayer,H-200),sw=IceLabSchematic.width,sh=IceLabSchematic.height,out=[],seen=new Set();const add=(cx,cy)=>{const l=Math.floor(cx-sw/2),t=Math.floor(cy-sh/2),k=l+','+t;if(l<90||t<surf+135||l+sw>W-90||t+sh>under-85||seen.has(k))return;seen.add(k);out.push({l,t});};const shrine=Rect('calamity:structure:iceShrine:',46,32);if(shrine){const cx=(shrine.l+shrine.r)/2,cy=(shrine.t+shrine.b)/2;for(const dx of [-620,620,-480,480,-340,340,-240,240])for(const dy of [-180,-80,40,140,220])add(cx+dx,cy+dy);}const xs=[];for(let x=Math.floor(W*.08);x<=Math.floor(W*.92);x+=Math.max(110,Math.floor(W/28)))xs.push(x);const ys=[];for(let y=surf+170;y<=under-130;y+=Math.max(75,Math.floor((under-surf)/11)))ys.push(y);const grid=[];for(const y of ys)for(const x of xs)grid.push({x,y,h:Hash(x*73856093^y*19349663)});grid.sort((a,b)=>a.h-b.h);for(const c of grid)add(c.x,c.y);return out.slice(0,280);}
function Reserved(left,top){const a={l:left,t:top,r:left+IceLabSchematic.width,b:top+IceLabSchematic.height};for(const r of [Rect('calamity:structure:iceShrine:',46,32),Rect('calamity:structure:jungleLab:',90,87),Rect('calamity:structure:planetoidLab:',105,125),Rect('calamity:structure:giantHive:'),Rect('calamity:structure:vernalPass:',276,208),Rect('calamity:structure:graniteShrine:',17,18),Rect('calamity:structure:marbleShrine:',22,18),Rect('calamity:structure:mechanicShed:')])if(Overlap(a,r,65))return true;return false;}
function Probe(c,relaxed=false){if(Reserved(c.l,c.t))return false;let ice=0,active=0,bad=0;const w=IceLabSchematic.width,h=IceLabSchematic.height;for(let gy=0;gy<PROBE_Y;gy++)for(let gx=0;gx<PROBE_X;gx++){const x=c.l-18+Math.floor((w+36)*(gx+.5)/PROBE_X),y=c.t+Math.floor(h*(gy+.5)/PROBE_Y),t=TileAt(x,y);if(!t)continue;const type=I(t.type,-1),wall=I(t.wall,0);if(Active(t)){active++;if(type===147||type===161)ice++;if(type===59||type===60||type===70||type===71||type===25||type===203||type===226)bad++;}if(wall===87||wall===3||wall===83)bad++;}const need=relaxed?16:23;return bad===0&&active>=30&&ice>=need;}
function Save(r){WorldDB.set(KEY+'generated',r?.generated===true);for(const k of ['left','top','width','height','centerX','centerY','centerWorldX','centerWorldY','applied'])WorldDB.set(KEY+k,I(r?.[k],-1));WorldDB.set(KEY+'sourceSha256',String(r?.sourceSha256||''));WorldDB.set(KEY+'source','official-ice-lab-incremental-v1');const ch=Array.isArray(r?.chests)?r.chests:[];WorldDB.set(KEY+'chestCount',ch.length);for(let i=0;i<ch.length;i++){const c=ch[i]||{},p=KEY+`chest:${i}:`;WorldDB.set(p+'x',I(c.x,-1));WorldDB.set(p+'y',I(c.y,-1));WorldDB.set(p+'index',I(c.index,-1));WorldDB.set(p+'filled',I(c.filled,0));WorldDB.set(p+'kind',String(c.kind||'security'));}try{WorldDB.Instance?.Save();}catch(e){Log(`metadata save deferred: ${e}`);}}
export class IceLabGenerationSystem extends ModSystem{
 constructor(){super();this.Reset();}
 Reset(){this.Delay=360;this.Candidates=[];this.Cursor=0;this.Session=null;this.Done=false;this.Relaxed=false;}
 OnWorldLoad(){this.Reset();}OnWorldUnload(){this.Reset();}
 Update(){if(this.Done||!WorldDB.Instance||Terraria.Main.gameMenu===true)return;if(WorldDB.get(KEY+'generated')===true){this.Done=true;return;}if(this.Delay-->0)return;if(!PostLoadWorkCoordinator.TryEnter('IceLab'))return;try{if(!this.Session){if(this.Candidates.length===0){this.Candidates=CandidateList();this.Cursor=0;Log(`bounded snow search started; candidates=${this.Candidates.length}, probes=${PROBE_X*PROBE_Y}/candidate.`);}let found=null;for(let n=0;n<1&&this.Cursor<this.Candidates.length;n++){const c=this.Candidates[this.Cursor++];if(Probe(c,this.Relaxed)){found=c;break;}}if(!found){if(this.Cursor>=this.Candidates.length&&!this.Relaxed){this.Relaxed=true;this.Candidates=CandidateList();this.Cursor=0;Log('strict search exhausted; retrying once with relaxed snow density.');return;}if(this.Cursor>=this.Candidates.length){Log('no safe Underground Snow location found; generation aborted without touching terrain.');this.Done=true;}return;}this.Session=IceLabRuntime.CreateSession(found.l,found.t);Log(`official 77x92 Ice Laboratory started at ${found.l},${found.t}; tileBudget=${BUDGET}.`);}const s=IceLabRuntime.StepSession(this.Session,BUDGET);if(!s.done)return;if(s.result?.generated===true){Save(s.result);Log(`laboratory committed; center=${s.result.centerX},${s.result.centerY}, chests=${s.result.chests?.length||0}.`);}else Log(`laboratory aborted safely: ${s.result?.reason||'unknown'}.`);this.Done=true;PostLoadWorkCoordinator.Release('IceLab');}catch(e){Log(`incremental generation aborted safely: ${e}`);this.Done=true;PostLoadWorkCoordinator.Release('IceLab');}}
}
