import { Terraria } from './../../TL/ModImports.js';
import { ModSystem } from './../../TL/ModSystem.js';
import { WorldDB } from './../../TL/WorldDB.js';
import { PostLoadWorkCoordinator } from './../../Core/PostLoadWorkCoordinator.js';
import { OnyxLabRuntime } from './../../Core/OnyxLabRuntime.js';
import { OnyxLabSchematic } from './../../Data/OfficialSchematics/OnyxLabSchematic.js';
const KEY='calamity:structure:onyxLab:',BUDGET=16,PROBE_X=13,PROBE_Y=7;
function I(v,f=0){const n=Math.floor(Number(v));return Number.isFinite(n)?n:f;}
function Active(t){try{return !!t&&t['bool active()']()===true;}catch(e){return false;}}
function TileAt(x,y){try{return Terraria.Main.tile.get_Item(I(x),I(y));}catch(e){return null;}}
function Busy(){try{return Terraria.WorldGen.isGeneratingOrLoadingWorld===true;}catch(e){return true;}}
function Log(s){try{tl.log(`[CalamityPort OnyxLabDeferred] ${s}`);}catch(e){}}
function Rect(prefix,defW=0,defH=0){if(!WorldDB.Instance||WorldDB.get(prefix+'generated')!==true)return null;const l=I(WorldDB.get(prefix+'left'),-1),t=I(WorldDB.get(prefix+'top'),-1),w=I(WorldDB.get(prefix+'width'),defW),h=I(WorldDB.get(prefix+'height'),defH);return l>=0&&t>=0&&w>0&&h>0?{l,t,r:l+w,b:t+h}:null;}
function Overlap(a,b,p=45){return !!a&&!!b&&a.l<b.r+p&&a.r>b.l-p&&a.t<b.b+p&&a.b>b.t-p;}
function Reserved(l,t){const a={l,t,r:l+OnyxLabSchematic.width,b:t+OnyxLabSchematic.height};const workshops=[Rect('calamity:structure:planetoidLab:',105,125),Rect('calamity:structure:jungleLab:',90,87),Rect('calamity:structure:iceLab:',77,92),Rect('calamity:structure:sunkenSeaLab:',119,93),Rect('calamity:structure:underworldLab:',139,75)];for(const r of workshops)if(Overlap(a,r,240))return true;const structures=[Rect('calamity:structure:giantHive:'),Rect('calamity:structure:vernalPass:'),Rect('calamity:structure:roxShrine:'),Rect('calamity:structure:shimmerShrine:'),Rect('calamity:structure:mechanicShed:'),Rect('calamity:structure:graniteShrine:'),Rect('calamity:structure:desertShrine:')];for(const r of structures)if(Overlap(a,r,55))return true;return false;}
function Hash(x){x=(x^61)^(x>>>16);x=(x+(x<<3))|0;x^=x>>>4;x=Math.imul(x,0x27d4eb2d);x^=x>>>15;return x>>>0;}
function Candidates(){const W=I(Terraria.Main.maxTilesX,4200),H=I(Terraria.Main.maxTilesY,1200),sw=OnyxLabSchematic.width,sh=OnyxLabSchematic.height,x0=Math.max(45,Math.floor(W*.30)),x1=Math.min(W-sw-45,Math.floor(W*.70)),y0=Math.max(I(Terraria.Main.rockLayer,450)+35,Math.floor(H*.55)),y1=Math.min(I(Terraria.Main.UnderworldLayer,H-200)-sh-45,Math.floor(H*.80));const out=[];if(x1<x0||y1<y0)return out;const sx=Math.max(34,Math.floor((x1-x0)/15)),sy=Math.max(28,Math.floor((y1-y0)/10));for(let y=y0;y<=y1;y+=sy)for(let x=x0;x<=x1;x+=sx)out.push({l:x,t:y,h:Hash(x*73856093^y*19349663)});for(let n=0;n<96;n++){const h=Hash(n*2654435761),x=x0+(h%Math.max(1,x1-x0+1)),y=y0+(Hash(h^0x9e3779b9)%Math.max(1,y1-y0+1));out.push({l:x,t:y,h:Hash(h^0x85ebca6b)});}out.sort((a,b)=>a.h-b.h);const seen=new Set(),u=[];for(const c of out){const k=c.l+','+c.t;if(seen.has(k))continue;seen.add(k);u.push(c);}return u.slice(0,300);}
function MossLike(type){return type===179||type===180||type===181||type===182||type===183||type===184||type===381||type===382||type===383||type===384||type===385||type===386;}
function Probe(c,relaxed=false){if(Reserved(c.l,c.t))return false;let plain=0,active=0,bad=0,jungle=0,dungeon=0;const w=OnyxLabSchematic.width,h=OnyxLabSchematic.height;for(let gy=0;gy<PROBE_Y;gy++)for(let gx=0;gx<PROBE_X;gx++){const x=c.l-30+Math.floor((w+60)*(gx+.5)/PROBE_X),y=c.t+Math.floor(h*(gy+.5)/PROBE_Y),t=TileAt(x,y);if(!t)continue;const type=I(t.type,-1),wall=I(t.wall,0);if(Active(t)){active++;if(type===0||type===1||type===59||MossLike(type))plain++;if(type===60||type===70)jungle++;if(type===41||type===43||type===44||type===226)bad++;}if(wall===7||wall===8||wall===9||wall===87)dungeon++;}const needed=relaxed?0.20:0.30;return bad===0&&dungeon===0&&jungle<=(relaxed?2:0)&&active>=Math.floor(PROBE_X*PROBE_Y*.22)&&plain>=Math.floor(PROBE_X*PROBE_Y*needed);}
function Save(r){WorldDB.set(KEY+'generated',r?.generated===true);for(const k of ['left','top','width','height','centerX','centerY','centerWorldX','centerWorldY','applied'])WorldDB.set(KEY+k,I(r?.[k],-1));WorldDB.set(KEY+'sourceSha256',String(r?.sourceSha256||''));WorldDB.set(KEY+'source','official-cavern-onyx-lab-incremental-v1');const ch=Array.isArray(r?.chests)?r.chests:[];WorldDB.set(KEY+'chestCount',ch.length);for(let i=0;i<ch.length;i++){const c=ch[i]||{},p=KEY+`chest:${i}:`;WorldDB.set(p+'x',I(c.x,-1));WorldDB.set(p+'y',I(c.y,-1));WorldDB.set(p+'index',I(c.index,-1));WorldDB.set(p+'filled',I(c.filled,0));WorldDB.set(p+'kind',String(c.kind||'security'));}try{WorldDB.Instance?.Save();}catch(e){Log(`metadata save deferred: ${e}`);}}
export class OnyxLabGenerationSystem extends ModSystem{constructor(){super();this.Reset();}Reset(){this.Delay=660;this.Candidates=[];this.Cursor=0;this.Session=null;this.Done=false;this.Relaxed=false;}OnWorldLoad(){this.Reset();}OnWorldUnload(){this.Reset();}Update(){if(this.Done||Busy()||!WorldDB.Instance||Terraria.Main.gameMenu===true)return;if(WorldDB.get(KEY+'generated')===true){this.Done=true;return;}if(this.Delay-->0)return;if(!PostLoadWorkCoordinator.TryEnter('OnyxLab'))return;try{if(!this.Session){if(this.Candidates.length===0){this.Candidates=Candidates();this.Cursor=0;Log(`official cavern search started; candidates=${this.Candidates.length}.`);}let found=null;for(let n=0;n<1&&this.Cursor<this.Candidates.length;n++){const c=this.Candidates[this.Cursor++];if(Probe(c,this.Relaxed)){found=c;break;}}if(!found){if(this.Cursor>=this.Candidates.length&&!this.Relaxed){this.Relaxed=true;this.Candidates=Candidates();this.Cursor=0;Log('strict cavern search exhausted; retrying once with relaxed plain-stone density.');return;}if(this.Cursor>=this.Candidates.length){Log('no safe Cavern Laboratory location found; generation aborted without touching terrain.');this.Done=true;}return;}this.Session=OnyxLabRuntime.CreateSession(found.l,found.t);Log(`official ${OnyxLabSchematic.width}x${OnyxLabSchematic.height} Cavern/Onyx Laboratory started at ${found.l},${found.t}; tileBudget=${BUDGET}.`);}const s=OnyxLabRuntime.StepSession(this.Session,BUDGET);if(!s.done)return;if(s.result?.generated===true){Save(s.result);Log(`laboratory committed; center=${s.result.centerX},${s.result.centerY}, chests=${s.result.chests?.length||0}.`);try{Terraria.Main.NewText('Cavern Laboratory generated.',210,90,220);}catch(e){}}else Log(`laboratory aborted safely: ${s.result?.reason||'unknown'}.`);this.Done=true;PostLoadWorkCoordinator.Release('OnyxLab');}catch(e){Log(`incremental generation aborted safely: ${e}`);this.Done=true;PostLoadWorkCoordinator.Release('OnyxLab');}}}
