import { Terraria } from './../../TL/ModImports.js';
import { ModSystem } from './../../TL/ModSystem.js';
import { WorldDB } from './../../TL/WorldDB.js';
import { RoxShrineRuntime } from './../../Core/RoxShrineRuntime.js';
import { OfficialStructureMap } from './../../Core/OfficialStructureMap.js';
const KEY='calamity:structure:roxShrine:';
function N(v,f=0){const n=Math.floor(Number(v));return Number.isFinite(n)?n:f;}function Log(s){try{tl.log(`[CalamityPort RoxShrineDeferred] ${s}`);}catch(e){}}
function Reserve(prefix,w,h){if(WorldDB.get(prefix+'generated')!==true)return;const l=N(WorldDB.get(prefix+'left'),-1),t=N(WorldDB.get(prefix+'top'),-1);w=Math.max(1,N(WorldDB.get(prefix+'width'),w));h=Math.max(1,N(WorldDB.get(prefix+'height'),h));if(l>=0&&t>=0)OfficialStructureMap.Reserve(prefix,{left:l,top:t,right:l+w,bottom:t+h},4);}
function Sunken(){if(WorldDB.get('calamity:sunkensea:terrain:generated')!==true)return null;const cx=N(WorldDB.get('calamity:sunkensea:preview:centerX'),-1),cy=N(WorldDB.get('calamity:sunkensea:preview:centerY'),-1),w=Math.max(1,N(WorldDB.get('calamity:sunkensea:preview:width'),520)),h=Math.max(1,N(WorldDB.get('calamity:sunkensea:preview:height'),310));return cx<0||cy<0?null:{left:cx-Math.floor(w/2),top:cy-Math.floor(h/2),width:w,height:h};}
function PortWorld(){for(const p of ['mechanicShed','desertShrine','graniteShrine','surfaceShrine','iceShrine','mushroomShrine','marbleShrine'])if(WorldDB.get(`calamity:structure:${p}:generated`)===true)return true;return false;}
function Save(r){WorldDB.set(KEY+'generated',true);WorldDB.set(KEY+'pending',false);WorldDB.set(KEY+'searchStopped',false);WorldDB.set(KEY+'left',N(r.left,N(r.anchorX)));WorldDB.set(KEY+'top',N(r.top,N(r.anchorY)));WorldDB.set(KEY+'width',N(r.width,35));WorldDB.set(KEY+'height',N(r.height,35));WorldDB.set(KEY+'anchorX',N(r.anchorX));WorldDB.set(KEY+'anchorY',N(r.anchorY));WorldDB.set(KEY+'variant',N(r.variant,1));WorldDB.set(KEY+'roxX',N(r.anchorX)+16);WorldDB.set(KEY+'roxY',N(r.anchorY)+14);WorldDB.set(KEY+'roxRemoved',false);WorldDB.set(KEY+'customCells',JSON.stringify(r.customCells||[]));WorldDB.set(KEY+'source',String(r.source||'official-csch-delayed'));try{WorldDB.Instance.Save();}catch(e){}const v=ModSystem.getByName('RoxShrineVisualSystem');if(v&&v.Reload)v.Reload();}
export class RoxShrineGenerationSystem extends ModSystem{
 constructor(){super();this.Delay=10200;this.Search=null;this.Rounds=0;this.Done=false;this.Recovery=false;this.Last=-1;}
 Reset(){this.Delay=10200;this.Search=null;this.Rounds=0;this.Done=false;this.Recovery=false;this.Last=-1;}OnWorldLoad(){this.Reset();}OnWorldUnload(){this.Reset();}
 Recover(){if(this.Recovery)return;this.Recovery=true;if(WorldDB.get(KEY+'generated')===true||WorldDB.get(KEY+'pending')===true)return;}
 Begin(){OfficialStructureMap.Reset();for(const e of [['mechanicShed',30,21],['desertShrine',30,27],['graniteShrine',17,18],['surfaceShrine',56,36],['iceShrine',46,32],['mushroomShrine',35,42],['corruptionShrine',26,11],['crimsonShrine',54,19],['marbleShrine',23,44]])Reserve(`calamity:structure:${e[0]}:`,e[1],e[2]);this.Rounds++;this.Search=RoxShrineRuntime.Begin({maxX:N(Terraria.Main.maxTilesX,4200),maxY:N(Terraria.Main.maxTilesY,1200)},Sunken());Log(`incremental search started; round=${this.Rounds}, variant=${this.Search.variant}, candidates=${this.Search.candidates.length}, budget=12 reads/update.`);}
 Update(){try{if(Terraria.WorldGen.isGeneratingOrLoadingWorld===true)return;}catch(e){}if(this.Done||!WorldDB.Instance)return;this.Recover();if(this.Delay-->0)return;if(WorldDB.get(KEY+'generated')===true){this.Done=true;return;}if(WorldDB.get(KEY+'pending')!==true){this.Done=true;return;}if(N(WorldDB.get(KEY+'deferredVersion'),0)!==2){WorldDB.set(KEY+'pending',false);WorldDB.set(KEY+'stalePendingSuppressed',true);try{WorldDB.Instance.Save();}catch(e){}this.Done=true;Log('suppressed stale legacy pending marker; no background recovery scan started.');return;}if(WorldDB.get('calamity:structure:marbleShrine:generated')!==true&&WorldDB.get('calamity:structure:marbleShrine:searchStopped')!==true){this.Delay=300;return;}try{if(!this.Search)this.Begin();const step=RoxShrineRuntime.Step(this.Search,12);if(step.generated===true&&step.result){Save(step.result);this.Done=true;Log(`delayed placement complete; topLeft=${step.result.anchorX},${step.result.anchorY}, variant=${step.result.variant}, RoxTile=${step.result.anchorX+16},${step.result.anchorY+14}, reads=${this.Search.reads}, inspected=${this.Search.inspected}.`);return;}if(step.done===true){Log(`search round ${this.Rounds} failed; reason=${step.reason}, inspected=${step.inspected}, candidates=${step.candidates}, reads=${step.reads}.`);this.Search=null;this.Last=-1;if(this.Rounds>=4){WorldDB.set(KEY+'searchStopped',true);this.Done=true;Log('delayed placement stopped after four rounds; pending marker preserved for the next world load.');}else this.Delay=300;return;}const p=Math.floor((this.Search.reads||0)/16384);if(p>this.Last){this.Last=p;Log(`progress; variant=${this.Search.variant}, inspected=${this.Search.inspected}, candidate=${this.Search.index}/${this.Search.candidates.length}, reads=${this.Search.reads}.`);}this.Delay=8;}catch(e){Log(`incremental search threw: ${e}`);this.Search=null;if(++this.Rounds>=4){WorldDB.set(KEY+'searchStopped',true);this.Done=true;}else this.Delay=300;}}
}
