import { Terraria } from './../../TL/ModImports.js';
import { ModSystem } from './../../TL/ModSystem.js';
import { WorldDB } from './../../TL/WorldDB.js';
import { PostLoadWorkCoordinator } from './../../Core/PostLoadWorkCoordinator.js';
import { UnderworldLabRuntime } from './../../Core/UnderworldLabRuntime.js';
import { UnderworldLabSchematic } from './../../Data/OfficialSchematics/UnderworldLabSchematic.js';
const KEY='calamity:structure:underworldLab:',BUDGET=16,PROBE_X=11,PROBE_Y=6;
function I(v,f=0){const n=Math.floor(Number(v));return Number.isFinite(n)?n:f;}
function Active(t){try{return !!t&&t['bool active()']()===true;}catch(e){return false;}}
function TileAt(x,y){try{return Terraria.Main.tile.get_Item(I(x),I(y));}catch(e){return null;}}
function Busy(){try{return Terraria.WorldGen.isGeneratingOrLoadingWorld===true;}catch(e){return true;}}
function Log(s){try{tl.log(`[CalamityPort UnderworldLabDeferred] ${s}`);}catch(e){}}
function Rect(prefix,defW=0,defH=0){if(!WorldDB.Instance||WorldDB.get(prefix+'generated')!==true)return null;const l=I(WorldDB.get(prefix+'left'),-1),t=I(WorldDB.get(prefix+'top'),-1),w=I(WorldDB.get(prefix+'width'),defW),h=I(WorldDB.get(prefix+'height'),defH);return l>=0&&t>=0&&w>0&&h>0?{l,t,r:l+w,b:t+h}:null;}
function Overlap(a,b,p=45){return !!a&&!!b&&a.l<b.r+p&&a.r>b.l-p&&a.t<b.b+p&&a.b>b.t-p;}
function Reserved(l,t){const a={l,t,r:l+UnderworldLabSchematic.width,b:t+UnderworldLabSchematic.height};for(const r of [Rect('calamity:structure:roxShrine:'),Rect('calamity:structure:shimmerShrine:'),Rect('calamity:structure:sunkenSeaLab:',119,93),Rect('calamity:structure:iceLab:',77,92),Rect('calamity:structure:jungleLab:',90,87),Rect('calamity:structure:planetoidLab:',105,125)])if(Overlap(a,r,55))return true;return false;}
function Hash(x){x=(x^61)^(x>>>16);x=(x+(x<<3))|0;x^=x>>>4;x=Math.imul(x,0x27d4eb2d);x^=x>>>15;return x>>>0;}
function Candidates(){const W=I(Terraria.Main.maxTilesX,4200),H=I(Terraria.Main.maxTilesY,1200),sw=UnderworldLabSchematic.width,sh=UnderworldLabSchematic.height,dungeon=I(Terraria.Main.dungeonX,W/2),leftSide=dungeon>W/2;let x0,x1;if(leftSide){x0=Math.floor(W/12);x1=Math.floor(W/9);}else{x0=Math.floor(W*.82);x1=Math.floor(W*.925)-sw;}if(x1<x0){x0=Math.max(30,leftSide?30:W-sw-260);x1=Math.min(W-sw-30,x0+220);}const y0=Math.max(I(Terraria.Main.UnderworldLayer,H-200)+10,H-175),y1=Math.min(H-sh-18,H-118);const out=[];for(let y=y0;y<=y1;y+=5)for(let x=x0;x<=x1;x+=Math.max(10,Math.floor((x1-x0)/12)||10))out.push({l:x,t:y,h:Hash(x*73856093^y*19349663)});out.sort((a,b)=>a.h-b.h);return out.slice(0,220);}
function Probe(c,relaxed=false){if(Reserved(c.l,c.t))return false;let active=0,bad=0,ash=0;const w=UnderworldLabSchematic.width,h=UnderworldLabSchematic.height;for(let gy=0;gy<PROBE_Y;gy++)for(let gx=0;gx<PROBE_X;gx++){const x=c.l-18+Math.floor((w+36)*(gx+.5)/PROBE_X),y=c.t+Math.floor(h*(gy+.5)/PROBE_Y),t=TileAt(x,y);if(!t)continue;const type=I(t.type,-1),wall=I(t.wall,0);if(Active(t)){active++;if(type===57||type===58||type===76||type===75)ash++;if(type===41||type===43||type===44||type===226||type===25||type===203)bad++;}if(wall===87||wall===83||wall===3)bad++;}return bad===0&&active>=(relaxed?8:16)&&ash>=(relaxed?3:7);}
function Save(r){WorldDB.set(KEY+'generated',r?.generated===true);for(const k of ['left','top','width','height','centerX','centerY','centerWorldX','centerWorldY','applied'])WorldDB.set(KEY+k,I(r?.[k],-1));WorldDB.set(KEY+'sourceSha256',String(r?.sourceSha256||''));WorldDB.set(KEY+'source','official-underworld-lab-incremental-v1');const ch=Array.isArray(r?.chests)?r.chests:[];WorldDB.set(KEY+'chestCount',ch.length);for(let i=0;i<ch.length;i++){const c=ch[i]||{},p=KEY+`chest:${i}:`;WorldDB.set(p+'x',I(c.x,-1));WorldDB.set(p+'y',I(c.y,-1));WorldDB.set(p+'index',I(c.index,-1));WorldDB.set(p+'filled',I(c.filled,0));WorldDB.set(p+'kind',String(c.kind||'security'));}try{WorldDB.Instance?.Save();}catch(e){Log(`metadata save deferred: ${e}`);}}
export class UnderworldLabGenerationSystem extends ModSystem{constructor(){super();this.Reset();}Reset(){this.Delay=540;this.Candidates=[];this.Cursor=0;this.Session=null;this.Done=false;this.Relaxed=false;}OnWorldLoad(){this.Reset();}OnWorldUnload(){this.Reset();}Update(){if(this.Done||Busy()||!WorldDB.Instance||Terraria.Main.gameMenu===true)return;if(WorldDB.get(KEY+'generated')===true){this.Done=true;return;}if(this.Delay-->0)return;if(!PostLoadWorkCoordinator.TryEnter('UnderworldLab'))return;try{if(!this.Session){if(this.Candidates.length===0){this.Candidates=Candidates();this.Cursor=0;Log(`official-side underworld search started; candidates=${this.Candidates.length}.`);}let found=null;for(let n=0;n<1&&this.Cursor<this.Candidates.length;n++){const c=this.Candidates[this.Cursor++];if(Probe(c,this.Relaxed)){found=c;break;}}if(!found){if(this.Cursor>=this.Candidates.length&&!this.Relaxed){this.Relaxed=true;this.Candidates=Candidates();this.Cursor=0;Log('strict underworld search exhausted; retrying once with relaxed terrain density.');return;}if(this.Cursor>=this.Candidates.length){Log('no safe Underworld location found; generation aborted without touching terrain.');this.Done=true;}return;}this.Session=UnderworldLabRuntime.CreateSession(found.l,found.t);Log(`official ${UnderworldLabSchematic.width}x${UnderworldLabSchematic.height} Hell Laboratory started at ${found.l},${found.t}; tileBudget=${BUDGET}.`);}const s=UnderworldLabRuntime.StepSession(this.Session,BUDGET);if(!s.done)return;if(s.result?.generated===true){Save(s.result);Log(`laboratory committed; center=${s.result.centerX},${s.result.centerY}, chests=${s.result.chests?.length||0}.`);try{Terraria.Main.NewText('Underworld Laboratory generated.',255,90,70);}catch(e){}}else Log(`laboratory aborted safely: ${s.result?.reason||'unknown'}.`);this.Done=true;PostLoadWorkCoordinator.Release('UnderworldLab');}catch(e){Log(`incremental generation aborted safely: ${e}`);this.Done=true;PostLoadWorkCoordinator.Release('UnderworldLab');}}}
