import { Terraria } from './../TL/ModImports.js';
import { ModItem } from './../TL/ModItem.js';
import { WorldGenRand } from './../TL/Modules/WorldGenRand.js';
import { FillChestByIndex,EnsureChestAt,GetChestByIndex,IsChestEmpty } from './OfficialSchematicRuntime.js';
import { IceLabSchematic } from './../Data/OfficialSchematics/IceLabSchematic.js';
import { DecodeLabCell,ApplyLabProxy,ClearProxyCoating } from './LabPhysicalProxy.js';
const CHEST=21;
function I(v,f=0){const n=Math.floor(Number(v));return Number.isFinite(n)?n:f;}
function Clamp(v,a,b){return Math.max(a,Math.min(b,v));}
function TryCall(t,s,v){try{if(t&&typeof t[s]==='function'){t[s](v);return true;}}catch(e){}return false;}
function SetActive(t,v){try{t['void active(bool active)'](v===true);}catch(e){}}
function TileAt(x,y){try{return Terraria.Main.tile.get_Item(I(x),I(y));}catch(e){return null;}}
function InWorld(x,y,m=3){return x>=m&&y>=m&&x<I(Terraria.Main.maxTilesX)-m&&y<I(Terraria.Main.maxTilesY)-m;}
function Log(s){try{tl.log(`[CalamityPort IceLab] ${s}`);}catch(e){}}
function ApplyCell(x,y,m){const t=TileAt(x,y);if(!t)return false;if(!m.keepTile){if(m.kind>0){ApplyLabProxy(t,m);}else{SetActive(t,m.hasTile);t.type=m.tile;t.frameX=m.frameX;t.frameY=m.frameY;ClearProxyCoating(t);TryCall(t,'void halfBrick(bool halfBrick)',m.halfBlock);TryCall(t,'void slope(byte slope)',m.slope);TryCall(t,'void actuator(bool actuator)',m.hasActuator);TryCall(t,'void inActive(bool inActive)',m.isActuated);}t.liquid=Clamp(m.liquid,0,255);TryCall(t,'void liquidType(int liquidType)',m.liquidType);TryCall(t,'void color(byte color)',m.tileColor);TryCall(t,'void frameNumber(byte frameNumber)',m.tileFrameNumber);TryCall(t,'void wire(bool wire)',(m.wireData&1)!==0);TryCall(t,'void wire2(bool wire2)',(m.wireData&2)!==0);TryCall(t,'void wire3(bool wire3)',(m.wireData&4)!==0);TryCall(t,'void wire4(bool wire4)',(m.wireData&8)!==0);}if(!m.keepWall){t.wall=m.wall;TryCall(t,'void wallColor(byte wallColor)',m.wallColor);TryCall(t,'void wallFrameNumber(byte wallFrameNumber)',m.wallFrameNumber);TryCall(t,'void wallFrameX(int wallFrameX)',m.wallFrameX);TryCall(t,'void wallFrameY(int wallFrameY)',m.wallFrameY);}return true;}
function SetChestTiles(x,y){for(let dy=0;dy<2;dy++)for(let dx=0;dx<2;dx++){const t=TileAt(x+dx,y+dy);if(!t)continue;SetActive(t,true);t.type=CHEST;t.frameX=dx*18;t.frameY=dy*18;t.liquid=0;TryCall(t,'void liquidType(int liquidType)',0);TryCall(t,'void halfBrick(bool halfBrick)',false);TryCall(t,'void slope(byte slope)',0);TryCall(t,'void invisibleBlock(bool invisibleBlock)',true);}}
function Custom(name){try{return I(ModItem.getTypeByName(name),0);}catch(e){return 0;}}
function Contents(withLog){const a=[];if(withLog){const l=Custom('DraedonsLogSnowBiome'),s=Custom('EncryptedSchematicIce');if(l>0)a.push([l,1]);if(s>0)a.push([s,1]);}const seek=Custom('LabSeekingMechanism');if(seek>0)a.push([seek,1]);const d=Custom('DubiousPlating'),c=Custom('MysteriousCircuitry');if(d>0)a.push([d,WorldGenRand.NextInt(8,15)]);if(c>0)a.push([c,WorldGenRand.NextInt(7,13)]);a.push([8,WorldGenRand.NextInt(15,30)],[73,WorldGenRand.NextInt(5,12)],[188,WorldGenRand.NextInt(5,8)],[166,WorldGenRand.NextInt(6,8)]);const p=[2346,305,2323,2345];a.push([p[WorldGenRand.NextInt(0,p.length)],WorldGenRand.NextInt(3,6)]);return a;}
export function EnsureAndFillIceLabChest(x,y,withLog=false,onlyIfEmpty=true){x=I(x);y=I(y);if(!InWorld(x,y))return{success:false,index:-1,filled:0};SetChestTiles(x,y);const e=EnsureChestAt(x,y);if(e.chestIndex<0)return{success:false,index:-1,filled:0};const ch=GetChestByIndex(e.chestIndex);if(!ch)return{success:false,index:e.chestIndex,filled:0};if(onlyIfEmpty&&!IsChestEmpty(ch))return{success:true,index:e.chestIndex,filled:0,reason:'already-filled'};const n=FillChestByIndex(e.chestIndex,Contents(withLog));return{success:n>0,index:e.chestIndex,filled:n,reason:n>0?'filled':'fill-failed'};}
export const IceLabRuntime={
 CreateSession(left,top){const s=IceLabSchematic;return{left:I(left,-1),top:I(top,-1),cursor:0,total:s.width*s.height,chestCursor:0,chests:[],applied:0,done:false,started:Date.now()};},
 StepSession(q,budget=360){if(!q||q.done)return{done:true,result:q?.result||null,applied:0};const s=IceLabSchematic;if(!InWorld(q.left,q.top)||!InWorld(q.left+s.width-1,q.top+s.height-1)){q.done=true;q.result={generated:false,reason:'out-of-world'};return{done:true,result:q.result,applied:0};}let used=0;while(q.cursor<q.total&&used<budget){const n=q.cursor++,y=Math.floor(n/s.width),x=n-y*s.width,m=DecodeLabCell(s.palette[s.rows[y][x]]);if(ApplyCell(q.left+x,q.top+y,m))q.applied++;used++;}if(q.cursor<q.total)return{done:false,applied:used};while(q.chestCursor<s.chests.length&&used<budget){const c=s.chests[q.chestCursor],x=q.left+I(c[0]),y=q.top+I(c[1]),r=EnsureAndFillIceLabChest(x,y,q.chestCursor>0,true);q.chests.push({x,y,index:r.index,filled:r.filled,success:r.success,kind:String(c[2]||'security')});q.chestCursor++;used+=8;}if(q.chestCursor<s.chests.length)return{done:false,applied:used};q.done=true;const cx=q.left+Math.floor(s.width/2),cy=q.top+Math.floor(s.height/2);q.result={generated:true,left:q.left,top:q.top,width:s.width,height:s.height,centerX:cx,centerY:cy,centerWorldX:cx*16+8,centerWorldY:cy*16+8,chests:q.chests,applied:q.applied,sourceSha256:s.sourceSha256,elapsedMs:Date.now()-q.started};Log(`incremental complete left=${q.left},${q.top} applied=${q.applied} chests=${q.chests.filter(c=>c.success).length}/${s.chests.length} elapsed=${q.result.elapsedMs}ms.`);return{done:true,result:q.result,applied:used};}
};
