import { Terraria } from './../../TL/ModImports.js';
import { ModPlayer } from './../../TL/ModPlayer.js';
import { ModBuff } from './../../TL/ModBuff.js';
const MAX_PLAYERS=256,MAX_NPCS=200;
function PI(p){const direct=Math.floor(Number(p&&p.whoAmI));if(direct>=0&&direct<MAX_PLAYERS)return direct;try{const i=Math.floor(Number(Terraria.PlayerIndex(p)));if(i>=0&&i<MAX_PLAYERS)return i;}catch(e){}return -1;}
function NI(n){const i=Math.floor(Number(n&&n.whoAmI));return i>=0&&i<MAX_NPCS?i:-1;}
function Pow(power,eff,intense=1){return Math.pow(1+power*eff,intense);}
function DefaultStats(){return {power:0,usedDefense:0,maxDistance:500,attackTime:90,damageScaling:1,cooldown:180,mistPower:1,mistRate:0.35,coldMultiplier:1};}
export class FrozenCubePlayer extends ModPlayer{
    constructor(){super();this.Equipped=new Array(MAX_PLAYERS).fill(false);this.Vanity=new Array(MAX_PLAYERS).fill(false);this.Visuals=new Array(MAX_PLAYERS).fill(false);this.EquipGrace=new Array(MAX_PLAYERS).fill(0);this.VanityGrace=new Array(MAX_PLAYERS).fill(0);this.VisualGrace=new Array(MAX_PLAYERS).fill(0);this.CostApplied=new Array(MAX_PLAYERS).fill(false);this.UsedDefense=new Array(MAX_PLAYERS).fill(0);this.Power=new Array(MAX_PLAYERS).fill(0);this.ColdBoost=new Array(MAX_PLAYERS).fill(0);this.ElumphantBoost=new Array(MAX_PLAYERS).fill(0);this.StatCache=new Array(MAX_PLAYERS);for(let i=0;i<MAX_PLAYERS;i++)this.StatCache[i]=DefaultStats();this.NPCMultiplier=new Array(MAX_NPCS).fill(1);this.NPCOwner=new Array(MAX_NPCS).fill(-1);this.WindType=0;}
    Clear(p,full=false){const i=PI(p);if(i<0)return;this.Equipped[i]=false;this.Vanity[i]=false;this.Visuals[i]=false;this.CostApplied[i]=false;if(full){this.EquipGrace[i]=0;this.VanityGrace[i]=0;this.VisualGrace[i]=0;this.UsedDefense[i]=0;this.Power[i]=0;this.ColdBoost[i]=0;this.ElumphantBoost[i]=0;this.StatCache[i]=DefaultStats();}else{this.EquipGrace[i]=Math.max(0,(Number(this.EquipGrace[i])||0)-1);this.VanityGrace[i]=Math.max(0,(Number(this.VanityGrace[i])||0)-1);this.VisualGrace[i]=Math.max(0,(Number(this.VisualGrace[i])||0)-1);}}
    ResetEffects(p){this.Clear(p,false);}OnEnterWorld(p){this.Clear(p,true);}OnRespawn(p){this.Clear(p,true);}UpdateDead(p){this.Clear(p,true);}
    Enable(p,visible,vanity=false){const i=PI(p);if(i<0)return -1;if(vanity){this.Vanity[i]=true;this.VanityGrace[i]=3;}else{this.Equipped[i]=true;this.EquipGrace[i]=3;}if(visible){this.Visuals[i]=true;this.VisualGrace[i]=3;}return i;}
    ApplyDefenseCost(p){const i=PI(p);if(i<0||this.CostApplied[i]||!this.Equipped[i])return this.UsedDefense[i]||0;let used=Math.floor(Math.max(0,Number(p.statDefense)||0)/3);p.statDefense=Math.max(0,Math.floor(Number(p.statDefense)||0)-used);this.CostApplied[i]=true;this.UsedDefense[i]=used;let effective=used;if(effective>110)effective=Math.floor(110*Math.pow(effective/110,0.15));const power=effective*0.05;this.Power[i]=power;const intense=1+power*0.2;this.ColdBoost[i]=Pow(power,0.8,intense)-1;this.ElumphantBoost[i]=Pow(power,1.35,intense)-1;this.StatCache[i]={power,usedDefense:used,maxDistance:500*Pow(power,0.3),attackTime:Math.max(12,Math.floor(90/Pow(power,0.5))),damageScaling:Pow(power,1.35,intense),cooldown:Math.max(20,Math.floor(180/Pow(power,0.5))),mistPower:Pow(power,1),mistRate:0.35*Pow(power,0.25),coldMultiplier:1+Number(this.ColdBoost[i]||0)};return used;}
    IsActive(owner){const i=Math.floor(Number(owner));return i>=0&&i<MAX_PLAYERS&&(this.Equipped[i]||this.Vanity[i]||Number(this.EquipGrace[i])>0||Number(this.VanityGrace[i])>0);}
    IsCombat(owner){const i=Math.floor(Number(owner));return i>=0&&i<MAX_PLAYERS&&(this.Equipped[i]||Number(this.EquipGrace[i])>0);}
    IsVisual(owner){const i=Math.floor(Number(owner));return i>=0&&i<MAX_PLAYERS&&(this.Visuals[i]||Number(this.VisualGrace[i])>0);}
    Stats(owner){const i=Math.floor(Number(owner));return i>=0&&i<MAX_PLAYERS?(this.StatCache[i]||DefaultStats()):DefaultStats();}
    ResetNPC(n){const i=NI(n);if(i>=0){this.NPCMultiplier[i]=1;this.NPCOwner[i]=-1;}}
    ApplyWindChilled(n,owner,duration){const i=NI(n),o=Math.floor(Number(owner));if(i<0)return false;if(!(this.WindType>0))this.WindType=Number(ModBuff.getTypeByName('WindChilled')||0);if(this.WindType>0)try{n['void AddBuff(int type, int time, bool quiet)'](Math.floor(this.WindType),Math.max(1,Math.floor(duration)),false);}catch(e){}const mult=this.Stats(o).coldMultiplier;if(mult>=Number(this.NPCMultiplier[i])||this.NPCOwner[i]===o){this.NPCMultiplier[i]=mult;this.NPCOwner[i]=o;}return true;}
    WindMultiplier(n){const i=NI(n);return i>=0?Math.max(1,Number(this.NPCMultiplier[i])||1):1;}
}
