import { Terraria, Modules } from './../../../TL/ModImports.js';
import { ModProjectile } from './../../../TL/ModProjectile.js';
import { ModBuff } from './../../../TL/ModBuff.js';
import { FrozenCubeTrackedIndices, FrozenCubeNPC, ScanFrozenCubeNPCs } from './../../../Core/FrozenCubeTargetRuntime.js';
import { FusionEntityData } from './../../../Core/FusionEntityData.js';
const { Vector2, Color, Rectangle }=Modules;const SpriteEffects=new NativeClass('Microsoft.Xna.Framework.Graphics','SpriteEffects');const NewProjectile=Terraria.Projectile['int NewProjectile(IEntitySource spawnSource, Vector2 position, Vector2 velocity, int Type, int Damage, float KnockBack, int Owner, float ai0, float ai1, float ai2, NewProjectileModifier modifer)'];const NewDust=Terraria.Dust['int NewDust(Vector2 Position, int Width, int Height, int Type, float SpeedX, float SpeedY, int Alpha, Color newColor, float Scale)'];function setArray(holder,name,index,value){try{let a=holder[name],need=Number(index)+1,len=Number(a&&a.Length);if(!Number.isFinite(len))len=Number(a&&a.length)||0;if(len<need){a=a.cloneResized(need);holder[name]=a;}try{a['void SetValue(Object value, int index)'](value,Number(index));return true;}catch(_){}try{a.set_Item(Number(index),value);return true;}catch(_){}return false;}catch(_){return false;}}
function N(v,f=0){const n=Number(v);return Number.isFinite(n)?n:f;}function player(o){const i=Math.floor(N(o,-1));if(i<0)return null;try{if(i===Math.floor(N(Terraria.Main.myPlayer,-2))&&Terraria.Main.LocalPlayer)return Terraria.Main.LocalPlayer;}catch(_){}try{return Terraria.Main.player.get_Item(i);}catch(_){return null;}}function validPlayer(p){return !!(p&&p.active!==false&&p.dead!==true);}function validNpc(n){return !!(n&&n.active&&N(n.life)>0&&n.friendly!==true&&n.dontTakeDamage!==true);}function source(p){try{return p.GetProjectileSource_FromThis();}catch(_){return null;}}function dust(p,id,count=1,scale=.8){for(let i=0;i<count;i++)try{const d=NewDust(p.position,p.width,p.height,id,(Math.random()-.5)*4,(Math.random()-.5)*4,60,Color.White,scale);let q=null;try{q=Terraria.Main.dust.get_Item(Number(d));}catch(_){}if(q)q.noGravity=true;}catch(_){}}
const TextureCache=new Map();function texture(path){if(TextureCache.has(path))return TextureCache.get(path);let t=null;try{t=tl.texture.load(path);}catch(_){}TextureCache.set(path,t||null);return t;}function hasBuff(pl,type){if(!pl||!(type>0))return false;try{return Math.floor(N(pl.FindBuffIndex(type),-1))>=0;}catch(_){return false;}}function drawFrost(p,light){try{const tex=texture('Textures/Projectiles/Summon/FrostBlossom.png');if(!tex)return true;const pos=Vector2.new(N(p.Center.X)-N(Terraria.Main.screenPosition.X),N(p.Center.Y)-N(Terraria.Main.screenPosition.Y)+N(p.gfxOffY));const src=Rectangle.new(0,0,36,40),origin=Vector2.new(18,20);let color=light;try{color=p.GetAlpha(light);}catch(_){}const draw=Terraria.Main.spriteBatch['void Draw(Texture2D texture, Vector2 position, Nullable`1 sourceRectangle, Color color, float rotation, Vector2 origin, float scale, SpriteEffects effects, float layerDepth)'];if(!draw)return true;draw(tex,pos,src,color,N(p.rotation),origin,N(p.scale,1),SpriteEffects.None,0);return false;}catch(_){return true;}}
function findTarget(p){ScanFrozenCubeNPCs(6);let best=null,bd=500*500;for(const i of FrozenCubeTrackedIndices()){const n=FrozenCubeNPC(i);if(!validNpc(n))continue;const dx=N(n.Center.X)-N(p.Center.X),dy=N(n.Center.Y)-N(p.Center.Y),d=dx*dx+dy*dy;if(d<bd){bd=d;best=n;}}return best;}
export class FrostBlossom extends ModProjectile{
 constructor(){super();this.Texture='Projectiles/Summon/FrostBlossom';}
 SetStaticDefaults(){setArray(Terraria.Main,'projPet',this.Type,true); setArray(Terraria.ID.ProjectileID.Sets,'MinionSacrificable',this.Type,true);setArray(Terraria.ID.ProjectileID.Sets,'MinionTargetingFeature',this.Type,true);}
 SetDefaults(){const p=this.Projectile;p.width=36;p.height=40;p.netImportant=true;p.friendly=true;p.hostile=false;p.ignoreWater=true;p.minionSlots=1;p.timeLeft=90000;p.penetrate=-1;p.tileCollide=false;p.minion=true;p.aiStyle=-1;}
 OnSpawn(p){if(!(N(p.originalDamage)>0))p.originalDamage=Math.max(1,Math.floor(N(p.damage,10)));if(!(N(p.damage)>0))p.damage=Math.max(1,Math.floor(N(p.originalDamage,10)));FusionEntityData.GetProjectileBag(p,'frostFlower',()=>({age:0,cool:0,scan:0,target:-1}));dust(p,67,12,1);}
 AI(p){const pl=player(p.owner),s=FusionEntityData.GetProjectileBag(p,'frostFlower',()=>({age:0,cool:0,scan:0,target:-1}));if(!validPlayer(pl)){p.Kill();return;}const b=Number(ModBuff.getTypeByName('FrostBlossomBuff')||0);if(!(b>0&&hasBuff(pl,b))){try{p.Kill();}catch(_){p.active=false;}return;}try{pl.AddBuff(b,2,true);}catch(_){}const c=Terraria.PlayerCenter(pl),gy=N(pl.gfxOffY),grav=N(pl.gravDir,1),cy=N(c.Y)+(grav<0?60:-60)+gy;p.position=Vector2.new(N(c.X)-18,cy-20);p.velocity=Vector2.Zero;p.rotation=grav<0?Math.PI:0;p.scale=1+Math.sin(s.age/40)*.085;p.timeLeft=2;s.age++;if(s.scan--<=0){const n=findTarget(p);s.target=n?Math.floor(N(n.whoAmI,-1)):-1;s.scan=12;}if(s.cool>0)s.cool--;const n=s.target>=0?FrozenCubeNPC(s.target):null;if(validNpc(n)&&s.cool<=0&&Number(p.owner)===Number(Terraria.Main.myPlayer)){const dx=N(n.Center.X)-N(p.Center.X),dy=N(n.Center.Y)-N(p.Center.Y),l=Math.sqrt(dx*dx+dy*dy)||1,t=Number(ModProjectile.getTypeByName('FrostBeam')||0);if(t>0)NewProjectile(source(p),p.Center,Vector2.new(dx/l*20,dy/l*20),t,Math.max(1,Math.floor(N(p.damage,10))),N(p.knockBack,2),p.owner,0,0,0,null);s.cool=35;}}
 PreDraw(p,light){return drawFrost(p,light);}
 OnKill(p){}
}
export class FrostBeam extends ModProjectile{
 SetStaticDefaults(){setArray(Terraria.ID.ProjectileID.Sets,'MinionShot',this.Type,true);}
 constructor(){super();this.Texture='Projectiles/Summon/FrostBeam';}
 SetDefaults(){const p=this.Projectile;p.width=4;p.height=4;p.friendly=true;p.penetrate=1;p.timeLeft=50;p.extraUpdates=4;p.aiStyle=-1;}
 AI(p){p.rotation=Math.atan2(N(p.velocity.Y),N(p.velocity.X))+Math.PI/2;if(N(p.timeLeft)%2===0)dust(p,67,1,.75);}
 OnHitNPC(p,npc){try{npc.AddBuff(Terraria.ID.BuffID.Frostburn,120,false);}catch(_){} }
 PreKill(p){const c=p.Center;try{p['void Resize(int newWidth, int newHeight)'](70,70);}catch(_){p.width=70;p.height=70;p.Center=c;}p.maxPenetrate=-1;p.penetrate=-1;p.usesLocalNPCImmunity=true;p.localNPCHitCooldown=10;p.damage=Math.max(1,Math.floor(N(p.damage)/3));try{p.Damage();}catch(_){}dust(p,67,10,1);return true;}
}
